// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const CreateSessionRequestSchema = z.object({
  body: z.string(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Session created
 */
export const CreateSessionResponseSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Session created",
  });

export const DeleteSessionRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    session: z.string().register(z.globalRegistry, {
      description: "The identifier of the session to delete",
    }),
  }),
  query: z.never().optional(),
});
