// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type CreateSessionRequest = {
  body: string;
  path?: never;
  query?: never;
  url: "/whip/endpoint";
};

export type CreateSessionErrors = {
  /**
   * Bad request syntax or unsupported method
   */
  400: string;
  /**
   * Conflict
   */
  409: string;
};

export type CreateSessionError = CreateSessionErrors[keyof CreateSessionErrors];

export type CreateSessionResponses = {
  /**
   * Session created
   */
  201: string;
};

export type CreateSessionResponse =
  CreateSessionResponses[keyof CreateSessionResponses];

export type DeleteSessionRequest = {
  body?: never;
  path: {
    /**
     * The identifier of the session to delete
     */
    session: string;
  };
  query?: never;
  url: "/whip/resource/{session}";
};

export type DeleteSessionErrors = {
  /**
   * Conflict
   */
  409: string;
};

export type DeleteSessionError = DeleteSessionErrors[keyof DeleteSessionErrors];

export type DeleteSessionResponses = {
  /**
   * Session deleted
   */
  200: unknown;
};
