# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.0
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: webstream
description: Broadcast streaming app 🎤
docs: true
docsurl: https://radio-aktywne.github.io/webstream
envprefix: WEBSTREAM
imagename: apps/webstream
keyprefix: webstream
port: 13000
registry: true
releases: true
reponame: webstream
repourl: https://github.com/radio-aktywne/webstream
