services:
  poppy:
    build:
      context: ./
      network: host
    environment:
      - "POPPY__SERVER__HOST=${POPPY__SERVER__HOST:-0.0.0.0}"
      - "POPPY__SERVER__PORT=${POPPY__SERVER__PORT:-10410}"
      - "POPPY__EVENTS__WINDOW=${POPPY__EVENTS__WINDOW:-PT1H}"
      - "POPPY__BEAVER__HTTP__SCHEME=${POPPY__BEAVER__HTTP__SCHEME:-http}"
      - "POPPY__BEAVER__HTTP__HOST=${POPPY__BEAVER__HTTP__HOST:-localhost}"
      - "POPPY__BEAVER__HTTP__PORT=${POPPY__BEAVER__HTTP__PORT:-10500}"
      - "POPPY__BEAVER__HTTP__PATH=${POPPY__BEAVER__HTTP__PATH:-}"
      - "POPPY__LORIS__HTTP__SCHEME=${POPPY__LORIS__HTTP__SCHEME:-http}"
      - "POPPY__LORIS__HTTP__HOST=${POPPY__LORIS__HTTP__HOST:-localhost}"
      - "POPPY__LORIS__HTTP__PORT=${POPPY__LORIS__HTTP__PORT:-10400}"
      - "POPPY__LORIS__HTTP__PATH=${POPPY__LORIS__HTTP__PATH:-}"
      - "POPPY__LORIS__WHIP__SCHEME=${POPPY__LORIS__WHIP__SCHEME:-http}"
      - "POPPY__LORIS__WHIP__HOST=${POPPY__LORIS__WHIP__HOST:-localhost}"
      - "POPPY__LORIS__WHIP__PORT=${POPPY__LORIS__WHIP__PORT:-10401}"
      - "POPPY__LORIS__WHIP__PATH=${POPPY__LORIS__WHIP__PATH:-}"
      - "POPPY__OCTOPUS__HTTP__SCHEME=${POPPY__OCTOPUS__HTTP__SCHEME:-http}"
      - "POPPY__OCTOPUS__HTTP__HOST=${POPPY__OCTOPUS__HTTP__HOST:-localhost}"
      - "POPPY__OCTOPUS__HTTP__PORT=${POPPY__OCTOPUS__HTTP__PORT:-10300}"
      - "POPPY__OCTOPUS__HTTP__PATH=${POPPY__OCTOPUS__HTTP__PATH:-}"
      - "POPPY__OCTOPUS__SRT__HOST=${POPPY__OCTOPUS__SRT__HOST:-localhost}"
      - "POPPY__OCTOPUS__SRT__PORT=${POPPY__OCTOPUS__SRT__PORT:-10300}"
    network_mode: host
