services:
  poppy:
    build:
      context: ./
      network: host
    environment:
      - "POPPY__APIS__BEAVER__HOST=${POPPY__APIS__BEAVER__HOST:-localhost}"
      - "POPPY__APIS__BEAVER__PATH=${POPPY__APIS__BEAVER__PATH:-}"
      - "POPPY__APIS__BEAVER__PORT=${POPPY__APIS__BEAVER__PORT:-10500}"
      - "POPPY__APIS__BEAVER__SCHEME=${POPPY__APIS__BEAVER__SCHEME:-http}"
      - "POPPY__APIS__ICANHAZDADJOKE__HOST=${POPPY__APIS__ICANHAZDADJOKE__HOST:-icanhazdadjoke.com}"
      - "POPPY__APIS__ICANHAZDADJOKE__PATH=${POPPY__APIS__ICANHAZDADJOKE__PATH:-}"
      - "POPPY__APIS__ICANHAZDADJOKE__PORT=${POPPY__APIS__ICANHAZDADJOKE__PORT:-}"
      - "POPPY__APIS__ICANHAZDADJOKE__SCHEME=${POPPY__APIS__ICANHAZDADJOKE__SCHEME:-https}"
      - "POPPY__APIS__LORIS__HOST=${POPPY__APIS__LORIS__HOST:-localhost}"
      - "POPPY__APIS__LORIS__PATH=${POPPY__APIS__LORIS__PATH:-}"
      - "POPPY__APIS__LORIS__PORT=${POPPY__APIS__LORIS__PORT:-10400}"
      - "POPPY__APIS__LORIS__SCHEME=${POPPY__APIS__LORIS__SCHEME:-http}"
      - "POPPY__APIS__OCTOPUS__HOST=${POPPY__APIS__OCTOPUS__HOST:-localhost}"
      - "POPPY__APIS__OCTOPUS__PATH=${POPPY__APIS__OCTOPUS__PATH:-}"
      - "POPPY__APIS__OCTOPUS__PORT=${POPPY__APIS__OCTOPUS__PORT:-10300}"
      - "POPPY__APIS__OCTOPUS__SCHEME=${POPPY__APIS__OCTOPUS__SCHEME:-http}"
      - "POPPY__APIS__WHIP__HOST=${POPPY__APIS__WHIP__HOST:-localhost}"
      - "POPPY__APIS__WHIP__PATH=${POPPY__APIS__WHIP__PATH:-}"
      - "POPPY__APIS__WHIP__PORT=${POPPY__APIS__WHIP__PORT:-10401}"
      - "POPPY__APIS__WHIP__SCHEME=${POPPY__APIS__WHIP__SCHEME:-http}"
      - "POPPY__DEBUG=${POPPY__DEBUG:-true}"
      - "POPPY__SERVER__HOST=${POPPY__SERVER__HOST:-0.0.0.0}"
      - "POPPY__SERVER__PORT=${POPPY__SERVER__PORT:-10410}"
      - "POPPY__SRT__OCTOPUS__HOST=${POPPY__SRT__OCTOPUS__HOST:-localhost}"
      - "POPPY__SRT__OCTOPUS__LATENCY=${POPPY__SRT__OCTOPUS__LATENCY:-PT0.2S}"
      - "POPPY__SRT__OCTOPUS__PORT=${POPPY__SRT__OCTOPUS__PORT:-10300}"
    network_mode: host
