/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/whip/endpoint": {
    /**
     * Create a session
     * @description Create a session to ingest a stream
     */
    post: operations["CreateSession"];
  };
  "/whip/resource/whip-client": {
    /**
     * Delete a session
     * @description Delete a session and stop the stream
     */
    delete: operations["DeleteSession"];
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * Create a session
   * @description Create a session to ingest a stream
   */
  CreateSession: {
    requestBody: {
      content: {
        "application/sdp": string;
      };
    };
    responses: {
      /** @description Session created */
      201: {
        headers: {
          /** @description URL to the created session resource */
          location?: string;
        };
        content: {
          "application/sdp": string;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "text/plain": string;
        };
      };
      /** @description Conflict */
      409: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
  /**
   * Delete a session
   * @description Delete a session and stop the stream
   */
  DeleteSession: {
    responses: {
      /** @description Session deleted */
      200: {
        content: never;
      };
      /** @description Conflict */
      409: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
}
