// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * STUN
 *
 * STUN configuration.
 */
export const StunSchema = z
  .object({
    host: z.string().register(z.globalRegistry, {
      description: "Host of the STUN server.",
    }),
    port: z.int().gte(1).lte(65535).register(z.globalRegistry, {
      description: "Port of the STUN server.",
    }),
  })
  .register(z.globalRegistry, {
    description: "STUN configuration.",
  });

/**
 * Duration of time.
 */
export const TimedeltaSchema = z.string().register(z.globalRegistry, {
  description: "Duration of time.",
});

/**
 * WebRTC
 *
 * WebRTC configuration.
 */
export const WebRtcSchema = z
  .object({
    latency: TimedeltaSchema.optional(),
    stun: StunSchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "WebRTC configuration.",
  });

/**
 * Result
 *
 * Result of the test.
 */
export const TestResponseResultSchema = z
  .object({
    success: z.boolean().register(z.globalRegistry, {
      description: "Indicates if the test was successful.",
    }),
    message: z.string().register(z.globalRegistry, {
      description: "Message returned from the test.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Result of the test.",
  });

/**
 * Parameters
 *
 * Parameters for testing.
 */
export const ParametersSchema = z
  .object({
    message: z.string().nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Parameters for testing.",
  });

export const TestRequestParametersSchema = ParametersSchema.nullable();

/**
 * EventType
 *
 * Event types.
 */
export const EventTypeSchema = z.enum(["test"]).register(z.globalRegistry, {
  description: "Event types.",
});

export const SubscribeRequestTypesSchema = z
  .union([z.string(), z.array(EventTypeSchema)])
  .nullable();

/**
 * SRT
 *
 * SRT configuration.
 */
export const SrtSchema = z
  .object({
    host: z.string().register(z.globalRegistry, {
      description: "Host of the SRT server.",
    }),
    latency: TimedeltaSchema.optional(),
    port: z.int().gte(1).lte(65535).register(z.globalRegistry, {
      description: "Port of the SRT server.",
    }),
    password: z.string().nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "SRT configuration.",
  });

/**
 * Format
 *
 * Audio format.
 */
export const FormatSchema = z.enum(["ogg"]).register(z.globalRegistry, {
  description: "Audio format.",
});

/**
 * Codec
 *
 * Audio codec.
 */
export const CodecSchema = z.enum(["opus"]).register(z.globalRegistry, {
  description: "Audio codec.",
});

/**
 * StreamInput
 *
 * Data for requesting a stream.
 */
export const StreamInputSchema = z
  .object({
    bitrate: z
      .int()
      .gte(32000)
      .lte(512000)
      .register(z.globalRegistry, {
        description: "Audio bitrate in bits per second.",
      })
      .optional()
      .default(256000),
    channels: z
      .int()
      .gte(1)
      .lte(8)
      .register(z.globalRegistry, {
        description: "Number of audio channels.",
      })
      .optional()
      .default(2),
    codec: CodecSchema.optional(),
    format: FormatSchema.optional(),
    metadata: z.record(z.string(), z.string()).nullish().default(null),
    samplerate: z
      .int()
      .gte(8000)
      .lte(192000)
      .register(z.globalRegistry, {
        description: "Audio sample rate in Hz.",
      })
      .optional()
      .default(48000),
    srt: SrtSchema,
    webrtc: WebRtcSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Data for requesting a stream.",
  });

/**
 * StreamDetails
 *
 * Details of the stream.
 */
export const StreamDetailsSchema = z
  .object({
    stun: StunSchema,
  })
  .register(z.globalRegistry, {
    description: "Details of the stream.",
  });

export const PingPingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingPingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const PingHeadpingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingHeadpingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const SseSubscribeRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      types: z.union([SubscribeRequestTypesSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, stream of Server-Sent Events follows
 */
export const SseSubscribeResponseSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Request fulfilled, stream of Server-Sent Events follows",
  });

export const StreamStreamRequestSchema = z.object({
  body: StreamInputSchema,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Document created, URL follows
 */
export const StreamStreamResponseSchema = StreamDetailsSchema;

export const TestTestRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      parameters: z.union([TestRequestParametersSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TestTestResponseSchema = TestResponseResultSchema;
