// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Result
 *
 * Result of the test.
 */
export type TestResponseResult = {
  /**
   * Success
   *
   * Indicates if the test was successful.
   */
  success: boolean;
  /**
   * Message
   *
   * Message returned from the test.
   */
  message: string;
};

export type TestRequestParameters = Parameters | null;

/**
 * Parameters
 *
 * Parameters for testing.
 */
export type Parameters = {
  /**
   * Message
   *
   * Optional message to include in the test.
   */
  message?: string | null;
};

export type SubscribeRequestTypes = string | Array<EventType> | null;

/**
 * EventType
 *
 * Event types.
 */
export type EventType = "test";

/**
 * StreamInput
 *
 * Data for requesting a stream.
 */
export type StreamInput = {
  codec?: Codec;
  format?: Format;
  srt: SrtServer;
  /**
   * STUN server configuration.
   */
  stun?: StunServer | null;
};

/**
 * STUNServer
 *
 * STUN server configuration.
 */
export type StunServer = {
  /**
   * Host
   *
   * Host of the STUN server.
   */
  host: string;
  /**
   * Port
   *
   * Port of the STUN server.
   */
  port: number;
};

/**
 * SRTServer
 *
 * SRT server configuration.
 */
export type SrtServer = {
  /**
   * Host
   *
   * Host of the SRT server.
   */
  host: string;
  /**
   * Port
   *
   * Port of the SRT server.
   */
  port: number;
  /**
   * Password
   *
   * Password to authenticate with the SRT server.
   */
  password?: string | null;
};

/**
 * Format
 *
 * Audio format.
 */
export type Format = "ogg";

/**
 * Codec
 *
 * Audio codec.
 */
export type Codec = "opus";

/**
 * StreamDetails
 *
 * Details of the stream.
 */
export type StreamDetails = {
  stun: StunServer;
  /**
   * Port
   *
   * Port to stream to.
   */
  port: number;
};

export type PingPingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingPingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingPingResponse = PingPingResponses[keyof PingPingResponses];

export type PingHeadpingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingHeadpingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingHeadpingResponse =
  PingHeadpingResponses[keyof PingHeadpingResponses];

export type SseSubscribeRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Types of events to subscribe to.
     */
    types?: SubscribeRequestTypes | string | null;
  };
  url: "/sse";
};

export type SseSubscribeErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type SseSubscribeError = SseSubscribeErrors[keyof SseSubscribeErrors];

export type SseSubscribeResponses = {
  /**
   * Request fulfilled, stream of Server-Sent Events follows
   */
  200: string;
};

export type SseSubscribeResponse =
  SseSubscribeResponses[keyof SseSubscribeResponses];

export type StreamStreamRequest = {
  body: StreamInput;
  path?: never;
  query?: never;
  url: "/stream";
};

export type StreamStreamErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Conflict Exception
   */
  409: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type StreamStreamError = StreamStreamErrors[keyof StreamStreamErrors];

export type StreamStreamResponses = {
  /**
   * Document created, URL follows
   */
  201: StreamDetails;
};

export type StreamStreamResponse =
  StreamStreamResponses[keyof StreamStreamResponses];

export type TestTestRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Parameters for testing.
     */
    parameters?: TestRequestParameters | string | null;
  };
  url: "/test";
};

export type TestTestErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TestTestError = TestTestErrors[keyof TestTestErrors];

export type TestTestResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: TestResponseResult;
};

export type TestTestResponse = TestTestResponses[keyof TestTestResponses];
