info:
  title: loris
openapi: 3.1.0
paths:
  /ping:
    get:
      summary: Ping
      description: Ping.
      operationId: PingPing
      responses:
        "204":
          description: Request fulfilled, nothing follows
          headers:
            cache-control:
              schema:
                type: string
              required: false
              deprecated: false
              allowEmptyValue: false
              allowReserved: false
          content:
            application/json:
              schema:
                type: "null"
      deprecated: false
    head:
      summary: Ping headers
      description: Ping headers.
      operationId: PingHeadping
      responses:
        "204":
          description: Request fulfilled, nothing follows
          headers:
            cache-control:
              schema:
                type: string
              required: false
              deprecated: false
              allowEmptyValue: false
              allowReserved: false
          content:
            application/json:
              schema:
                type: "null"
      deprecated: false
  /stream:
    post:
      summary: Request a stream
      description: Request a stream.
      operationId: StreamStream
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StreamRequestData"
        required: true
      responses:
        "201":
          description: Document created, URL follows
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamResponseData"
        "400":
          description: Bad request syntax or unsupported method
          content:
            application/json:
              schema:
                properties:
                  status_code:
                    type: integer
                  detail:
                    type: string
                  extra:
                    additionalProperties: {}
                    type:
                      - "null"
                      - object
                      - array
                type: object
                required:
                  - detail
                  - status_code
                description: Validation Exception
                examples:
                  - status_code: 400
                    detail: Bad Request
                    extra: {}
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                properties:
                  status_code:
                    type: integer
                  detail:
                    type: string
                  extra:
                    additionalProperties: {}
                    type:
                      - "null"
                      - object
                      - array
                type: object
                required:
                  - detail
                  - status_code
                description: Conflict Exception
                examples:
                  - status_code: 409
                    detail: Conflict
                    extra: {}
      deprecated: false
components:
  schemas:
    SRTServer:
      properties:
        host:
          type: string
        port:
          type: integer
        password:
          oneOf:
            - type: "null"
            - type: string
      type: object
      required:
        - host
        - port
      title: SRTServer
      description: SRT server configuration.
    STUNServer:
      properties:
        host:
          type: string
        port:
          type: integer
      type: object
      required:
        - host
        - port
      title: STUNServer
    StreamRequestData:
      properties:
        codec:
          type: string
          enum:
            - opus
          description: Audio codec.
          default: opus
        format:
          type: string
          enum:
            - ogg
          description: Audio format.
          default: ogg
        srt:
          $ref: "#/components/schemas/SRTServer"
        stun:
          oneOf:
            - type: "null"
            - $ref: "#/components/schemas/STUNServer"
          description: STUN server configuration.
      type: object
      required:
        - srt
      title: StreamRequestData
      description: Data for the request.
    StreamResponseData:
      properties:
        stun:
          $ref: "#/components/schemas/STUNServer"
        port:
          type: integer
          maximum: 65535
          minimum: 1
          description: Port to stream to.
      type: object
      required:
        - port
        - stun
      title: StreamResponseData
