openapi: "3.1.0"
info:
  title: loris
  version: "0.16.0"
paths:
  /ping:
    get:
      tags:
        - Ping
      summary: Ping
      description: Ping.
      operationId: PingPing
      responses:
        "204":
          description: Request fulfilled, nothing follows
          headers:
            Cache-Control:
              schema:
                type: string
              required: true
              deprecated: false
      deprecated: false
    head:
      tags:
        - Ping
      summary: Ping headers
      description: Ping headers.
      operationId: PingHeadping
      responses:
        "204":
          description: Request fulfilled, nothing follows
          headers:
            Cache-Control:
              schema:
                type: string
              required: true
              deprecated: false
      deprecated: false
  /sse:
    get:
      tags:
        - SSE
      summary: Get SSE stream
      description: Get a stream of Server-Sent Events.
      operationId: SseSubscribe
      parameters:
        - name: types
          in: query
          schema:
            oneOf:
              - anyOf:
                  - $ref: "#/components/schemas/SubscribeRequestTypes"
                  - type: string
                    contentMediaType: application/json
                    contentSchema:
                      $ref: "#/components/schemas/SubscribeRequestTypes"
                title: SubscribeRequestTypes
              - type: "null"
            description: Types of events to subscribe to.
          description: Types of events to subscribe to.
          required: false
          deprecated: false
          allowEmptyValue: false
          allowReserved: false
      responses:
        "200":
          description: Request fulfilled, stream of Server-Sent Events follows
          headers:
            Cache-Control:
              schema:
                type: string
              required: true
              deprecated: false
            Connection:
              schema:
                type: string
              required: true
              deprecated: false
          content:
            text/event-stream:
              schema:
                type: string
        "400":
          description: Bad request syntax or unsupported method
          content:
            application/json:
              schema:
                properties:
                  status_code:
                    type: integer
                  detail:
                    type: string
                  extra:
                    additionalProperties: {}
                    type:
                      - "null"
                      - object
                      - array
                type: object
                required:
                  - detail
                  - status_code
                description: Validation Exception
                examples:
                  - status_code: 400
                    detail: Bad Request
                    extra: {}
      deprecated: false
  /stream:
    post:
      tags:
        - Stream
      summary: Request a stream
      description: Request a stream.
      operationId: StreamStream
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StreamInput"
        required: true
      responses:
        "201":
          description: Document created, URL follows
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamDetails"
        "400":
          description: Bad request syntax or unsupported method
          content:
            application/json:
              schema:
                properties:
                  status_code:
                    type: integer
                  detail:
                    type: string
                  extra:
                    additionalProperties: {}
                    type:
                      - "null"
                      - object
                      - array
                type: object
                required:
                  - detail
                  - status_code
                description: Validation Exception
                examples:
                  - status_code: 400
                    detail: Bad Request
                    extra: {}
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                properties:
                  status_code:
                    type: integer
                  detail:
                    type: string
                  extra:
                    additionalProperties: {}
                    type:
                      - "null"
                      - object
                      - array
                type: object
                required:
                  - detail
                  - status_code
                description: Conflict Exception
                examples:
                  - status_code: 409
                    detail: Conflict
                    extra: {}
      deprecated: false
  /test:
    get:
      tags:
        - Test
      summary: Test
      description: Test.
      operationId: TestTest
      parameters:
        - name: parameters
          in: query
          schema:
            oneOf:
              - anyOf:
                  - $ref: "#/components/schemas/TestRequestParameters"
                  - type: string
                    contentMediaType: application/json
                    contentSchema:
                      $ref: "#/components/schemas/TestRequestParameters"
                title: TestRequestParameters
              - type: "null"
            description: Parameters for testing.
          description: Parameters for testing.
          required: false
          deprecated: false
          allowEmptyValue: false
          allowReserved: false
      responses:
        "200":
          description: Request fulfilled, document follows
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestResponseResult"
        "400":
          description: Bad request syntax or unsupported method
          content:
            application/json:
              schema:
                properties:
                  status_code:
                    type: integer
                  detail:
                    type: string
                  extra:
                    additionalProperties: {}
                    type:
                      - "null"
                      - object
                      - array
                type: object
                required:
                  - detail
                  - status_code
                description: Validation Exception
                examples:
                  - status_code: 400
                    detail: Bad Request
                    extra: {}
      deprecated: false
components:
  schemas:
    Codec:
      type: string
      enum:
        - opus
      title: Codec
      description: Audio codec.
    EventType:
      type: string
      enum:
        - test
      title: EventType
      description: Event types.
    Format:
      type: string
      enum:
        - ogg
      title: Format
      description: Audio format.
    Parameters:
      properties:
        message:
          anyOf:
            - type: string
            - type: "null"
          title: Message
          description: Optional message to include in the test.
          default: null
      type: object
      title: Parameters
      description: Parameters for testing.
    SRT:
      properties:
        host:
          type: string
          title: Host
          description: Host of the SRT server.
        latency:
          $ref: "#/components/schemas/Timedelta"
        port:
          type: integer
          maximum: 65535
          minimum: 1
          title: Port
          description: Port of the SRT server.
        password:
          anyOf:
            - type: string
            - type: "null"
          title: Password
          description: Password to authenticate with the SRT server.
          default: null
      type: object
      required:
        - host
        - port
      title: SRT
      description: SRT configuration.
    STUN:
      properties:
        host:
          type: string
          title: Host
          description: Host of the STUN server.
        port:
          type: integer
          maximum: 65535
          minimum: 1
          title: Port
          description: Port of the STUN server.
      type: object
      required:
        - host
        - port
      title: STUN
      description: STUN configuration.
    StreamDetails:
      properties:
        stun:
          $ref: "#/components/schemas/STUN"
      type: object
      required:
        - stun
      title: StreamDetails
      description: Details of the stream.
    StreamInput:
      properties:
        bitrate:
          type: integer
          maximum: 512000
          minimum: 32000
          title: Bitrate
          description: Audio bitrate in bits per second.
          default: 256000
        channels:
          type: integer
          maximum: 8
          minimum: 1
          title: Channels
          description: Number of audio channels.
          default: 2
        codec:
          $ref: "#/components/schemas/Codec"
        format:
          $ref: "#/components/schemas/Format"
        metadata:
          anyOf:
            - additionalProperties:
                type: string
              type: object
            - type: "null"
          title: Metadata
          description: Metadata to attach to the stream.
          default: null
        samplerate:
          type: integer
          maximum: 192000
          minimum: 8000
          title: Samplerate
          description: Audio sample rate in Hz.
          default: 48000
        srt:
          $ref: "#/components/schemas/SRT"
        webrtc:
          $ref: "#/components/schemas/WebRTC"
      type: object
      required:
        - srt
      title: StreamInput
      description: Data for requesting a stream.
    SubscribeRequestTypes:
      anyOf:
        - type: string
        - items:
            $ref: "#/components/schemas/EventType"
          type: array
          uniqueItems: true
        - type: "null"
    TestRequestParameters:
      anyOf:
        - $ref: "#/components/schemas/Parameters"
        - type: "null"
    TestResponseResult:
      properties:
        success:
          type: boolean
          title: Success
          description: Indicates if the test was successful.
        message:
          type: string
          title: Message
          description: Message returned from the test.
      type: object
      required:
        - success
        - message
      title: Result
      description: Result of the test.
    Timedelta:
      type: string
      format: duration
      description: Duration of time.
      examples:
        - PT1H
    WebRTC:
      properties:
        latency:
          $ref: "#/components/schemas/Timedelta"
        stun:
          anyOf:
            - $ref: "#/components/schemas/STUN"
            - type: "null"
          description: STUN configuration.
          default: null
      type: object
      title: WebRTC
      description: WebRTC configuration.
