info:
  title: octopus
openapi: 3.1.0
paths:
  /check:
    get:
      summary: Check availability
      description: Check the availability of the stream.
      operationId: CheckCheck
      responses:
        "200":
          description: Request fulfilled, document follows
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Availability"
      deprecated: false
  /ping:
    get:
      summary: Ping
      description: Ping.
      operationId: PingPing
      responses:
        "204":
          description: Request fulfilled, nothing follows
          headers:
            cache-control:
              schema:
                type: string
              required: false
              deprecated: false
              allowEmptyValue: false
              allowReserved: false
          content:
            application/json:
              schema:
                type: "null"
      deprecated: false
    head:
      summary: Ping headers
      description: Ping headers.
      operationId: PingHeadping
      responses:
        "204":
          description: Request fulfilled, nothing follows
          headers:
            cache-control:
              schema:
                type: string
              required: false
              deprecated: false
              allowEmptyValue: false
              allowReserved: false
          content:
            application/json:
              schema:
                type: "null"
      deprecated: false
  /reserve:
    post:
      summary: Reserve a stream
      description: Reserve a stream.
      operationId: ReserveReserve
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReserveRequestData"
        required: true
      responses:
        "201":
          description: Document created, URL follows
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReserveResponseData"
        "400":
          description: Bad request syntax or unsupported method
          content:
            application/json:
              schema:
                properties:
                  status_code:
                    type: integer
                  detail:
                    type: string
                  extra:
                    additionalProperties: {}
                    type:
                      - "null"
                      - object
                      - array
                type: object
                required:
                  - detail
                  - status_code
                description: Validation Exception
                examples:
                  - status_code: 400
                    detail: Bad Request
                    extra: {}
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                properties:
                  status_code:
                    type: integer
                  detail:
                    type: string
                  extra:
                    additionalProperties: {}
                    type:
                      - "null"
                      - object
                      - array
                type: object
                required:
                  - detail
                  - status_code
                description: Conflict Exception
                examples:
                  - status_code: 409
                    detail: Conflict
                    extra: {}
        "422":
          description: Unprocessable Content
          content:
            application/json:
              schema:
                properties:
                  status_code:
                    type: integer
                  detail:
                    type: string
                  extra:
                    additionalProperties: {}
                    type:
                      - "null"
                      - object
                      - array
                type: object
                required:
                  - detail
                  - status_code
                description: Unprocessable Content Exception
                examples:
                  - status_code: 422
                    detail: Unprocessable Content
                    extra: {}
      deprecated: false
  /sse:
    get:
      summary: Get SSE stream
      description: Get a stream of Server-Sent Events.
      operationId: SseSubscribe
      responses:
        "200":
          description: Request fulfilled, document follows
          headers:
            content-length:
              schema:
                type: string
              description: File size in bytes
              required: false
              deprecated: false
              allowEmptyValue: false
              allowReserved: false
            last-modified:
              schema:
                type: string
                format: date-time
              description: Last modified data-time in RFC 2822 format
              required: false
              deprecated: false
              allowEmptyValue: false
              allowReserved: false
            etag:
              schema:
                type: string
              description: Entity tag
              required: false
              deprecated: false
              allowEmptyValue: false
              allowReserved: false
          content:
            "":
              schema:
                type: string
                contentMediaType: application/octet-stream
      deprecated: false
components:
  schemas:
    Availability:
      properties:
        event:
          oneOf:
            - type: "null"
            - type: string
              format: uuid
          description: Identifier of the event that is currently being streamed.
        checkedAt:
          type: string
          format: date-time
          description: Time in UTC at which the availability was checked.
      type: object
      required:
        - checkedAt
      title: Availability
    Credentials:
      properties:
        token:
          type: string
          description: Token to use to connect to the stream.
        expiresAt:
          type: string
          format: date-time
          description: Time in UTC at which the token expires if not used.
      type: object
      required:
        - expiresAt
        - token
      title: Credentials
      description: Credentials to use to connect to the stream.
    ReserveRequestData:
      properties:
        event:
          type: string
          format: uuid
          description: Identifier of the event to reserve the stream for.
        format:
          type: string
          enum:
            - ogg
          description: Format of the audio in the stream.
          default: ogg
        record:
          type: boolean
          description: Whether to record the stream.
          default: false
      type: object
      required:
        - event
      title: ReserveRequestData
      description: Data for the request.
    ReserveResponseData:
      properties:
        credentials:
          $ref: "#/components/schemas/Credentials"
        port:
          type: integer
          maximum: 65535
          minimum: 1
          description: Port to use to connect to the stream.
      type: object
      required:
        - credentials
        - port
      title: ReserveResponseData
