/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/check": {
    /**
     * Check availability
     * @description Check the availability of the stream.
     */
    get: operations["CheckCheck"];
  };
  "/ping": {
    /**
     * Ping
     * @description Ping.
     */
    get: operations["PingPing"];
    /**
     * Ping headers
     * @description Ping headers.
     */
    head: operations["PingHeadping"];
  };
  "/reserve": {
    /**
     * Reserve a stream
     * @description Reserve a stream.
     */
    post: operations["ReserveReserve"];
  };
  "/sse": {
    /**
     * Get SSE stream
     * @description Get a stream of Server-Sent Events.
     */
    get: operations["SseSubscribe"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Availability */
    Availability: {
      /** @description Identifier of the event that is currently being streamed. */
      event?: null | string;
      /**
       * Format: date-time
       * @description Time in UTC at which the availability was checked.
       */
      checkedAt: string;
    };
    /**
     * Credentials
     * @description Credentials to use to connect to the stream.
     */
    Credentials: {
      /** @description Token to use to connect to the stream. */
      token: string;
      /**
       * Format: date-time
       * @description Time in UTC at which the token expires if not used.
       */
      expiresAt: string;
    };
    /**
     * ReserveRequestData
     * @description Data for the request.
     */
    ReserveRequestData: {
      /**
       * Format: uuid
       * @description Identifier of the event to reserve the stream for.
       */
      event: string;
      /**
       * @description Format of the audio in the stream.
       * @default ogg
       * @enum {string}
       */
      format?: "ogg";
      /**
       * @description Whether to record the stream.
       * @default false
       */
      record?: boolean;
    };
    /** ReserveResponseData */
    ReserveResponseData: {
      credentials: components["schemas"]["Credentials"];
      /** @description Port to use to connect to the stream. */
      port: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * Check availability
   * @description Check the availability of the stream.
   */
  CheckCheck: {
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {};
        content: {
          "application/json": components["schemas"]["Availability"];
        };
      };
    };
  };
  /**
   * Ping
   * @description Ping.
   */
  PingPing: {
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        headers: {
          "cache-control"?: string;
        };
        content: {
          "application/json": null;
        };
      };
    };
  };
  /**
   * Ping headers
   * @description Ping headers.
   */
  PingHeadping: {
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        headers: {
          "cache-control"?: string;
        };
        content: {
          "application/json": null;
        };
      };
    };
  };
  /**
   * Reserve a stream
   * @description Reserve a stream.
   */
  ReserveReserve: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReserveRequestData"];
      };
    };
    responses: {
      /** @description Document created, URL follows */
      201: {
        headers: {};
        content: {
          "application/json": components["schemas"]["ReserveResponseData"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
      /** @description Conflict */
      409: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
      /** @description Unprocessable Content */
      422: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
  /**
   * Get SSE stream
   * @description Get a stream of Server-Sent Events.
   */
  SseSubscribe: {
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
          /** @description File size in bytes */
          "content-length"?: string;
          /** @description Last modified data-time in RFC 2822 format */
          "last-modified"?: string;
          /** @description Entity tag */
          etag?: string;
        };
        content: {
          "": string;
        };
      };
    };
  };
}
