/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/whip/endpoint": {
    delete?: never;
    get?: never;
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    /**
     * Create a session
     * @description Create a session to ingest a stream
     */
    post: operations["CreateSession"];
    put?: never;
    trace?: never;
  };
  "/whip/resource/{session}": {
    /**
     * Delete a session
     * @description Delete a session and stop the stream
     */
    delete: operations["DeleteSession"];
    get?: never;
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
};
export type webhooks = { [key: string]: never };
export type components = {
  headers: never;
  parameters: never;
  pathItems: never;
  requestBodies: never;
  responses: never;
  schemas: never;
};
export type $defs = { [key: string]: never };
export type operations = {
  CreateSession: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody: {
      content: {
        "application/sdp": string;
      };
    };
    responses: {
      /** @description Session created */
      201: {
        content: {
          "application/sdp": string;
        };
        headers: {
          [name: string]: unknown;
          /** @description URL to the created session resource */
          location?: string;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "text/plain": string;
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Conflict */
      409: {
        content: {
          "text/plain": string;
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  DeleteSession: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        /** @description The identifier of the session to delete */
        session: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session deleted */
      200: {
        content?: never;
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Conflict */
      409: {
        content: {
          "text/plain": string;
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
};
