// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const ReserveModelsNaiveDatetimeSchema = z.iso.datetime({
  offset: true,
  local: true,
});

export const CheckModelsNaiveDatetimeSchema = z.iso.datetime({
  offset: true,
  local: true,
});

/**
 * Result
 *
 * Result of the test.
 */
export const TestResponseResultSchema = z
  .object({
    success: z.boolean().register(z.globalRegistry, {
      description: "Indicates if the test was successful.",
    }),
    message: z.string().register(z.globalRegistry, {
      description: "Message returned from the test.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Result of the test.",
  });

/**
 * Parameters
 *
 * Parameters for testing.
 */
export const ParametersSchema = z
  .object({
    message: z.string().nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Parameters for testing.",
  });

export const TestRequestParametersSchema = ParametersSchema.nullable();

/**
 * EventType
 *
 * Event types.
 */
export const EventTypeSchema = z
  .enum(["test", "availability-changed"])
  .register(z.globalRegistry, {
    description: "Event types.",
  });

export const SubscribeRequestTypesSchema = z
  .union([z.string(), z.array(EventTypeSchema)])
  .nullable();

/**
 * Credentials
 *
 * Credentials for accessing the stream.
 */
export const CredentialsSchema = z
  .object({
    token: z.string().register(z.globalRegistry, {
      description: "Token to use to connect to the stream.",
    }),
    expiresAt: ReserveModelsNaiveDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Credentials for accessing the stream.",
  });

/**
 * Reservation
 *
 * Reservation of a stream.
 */
export const ReserveResponseReservationSchema = z
  .object({
    credentials: CredentialsSchema,
  })
  .register(z.globalRegistry, {
    description: "Reservation of a stream.",
  });

/**
 * Format
 *
 * Audio format.
 */
export const FormatSchema = z.enum(["ogg"]).register(z.globalRegistry, {
  description: "Audio format.",
});

/**
 * ReservationInput
 *
 * Data for reserving a stream.
 */
export const ReserveRequestDataSchema = z
  .object({
    event: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the event to reserve the stream for.",
    }),
    format: FormatSchema.optional(),
    record: z
      .boolean()
      .register(z.globalRegistry, {
        description: "Whether to record the stream.",
      })
      .optional()
      .default(false),
    metadata: z.record(z.string(), z.string()).nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Data for reserving a stream.",
  });

/**
 * Availability
 *
 * Availability of a stream.
 */
export const CheckResponseAvailabilitySchema = z
  .object({
    event: z.uuid().nullable(),
    checkedAt: CheckModelsNaiveDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Availability of a stream.",
  });

export const CheckCheckRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, document follows
 */
export const CheckCheckResponseSchema = CheckResponseAvailabilitySchema;

export const PingPingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingPingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const PingHeadpingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingHeadpingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const ReserveReserveRequestSchema = z.object({
  body: ReserveRequestDataSchema,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Document created, URL follows
 */
export const ReserveReserveResponseSchema = ReserveResponseReservationSchema;

export const SseSubscribeRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      types: z.union([SubscribeRequestTypesSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, stream of Server-Sent Events follows
 */
export const SseSubscribeResponseSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Request fulfilled, stream of Server-Sent Events follows",
  });

export const TestTestRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      parameters: z.union([TestRequestParametersSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TestTestResponseSchema = TestResponseResultSchema;
