// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Datetime in UTC.
 */
export type ReserveModelsUtcDatetime = string;

/**
 * Datetime in UTC.
 */
export type CheckModelsUtcDatetime = string;

/**
 * Result
 *
 * Result of the test.
 */
export type TestResponseResult = {
  /**
   * Success
   *
   * Indicates if the test was successful.
   */
  success: boolean;
  /**
   * Message
   *
   * Message returned from the test.
   */
  message: string;
};

export type TestRequestParameters = Parameters | null;

/**
 * Parameters
 *
 * Parameters for testing.
 */
export type Parameters = {
  /**
   * Message
   *
   * Optional message to include in the test.
   */
  message?: string | null;
};

export type SubscribeRequestTypes = string | Array<EventType> | null;

/**
 * EventType
 *
 * Event types.
 */
export type EventType = "test" | "availability-changed";

/**
 * Reservation
 *
 * Reservation of a stream.
 */
export type ReserveResponseReservation = {
  credentials: Credentials;
};

/**
 * Credentials
 *
 * Credentials for accessing the stream.
 */
export type Credentials = {
  /**
   * Token
   *
   * Token to use to connect to the stream.
   */
  token: string;
  expiresAt: ReserveModelsUtcDatetime;
};

/**
 * ReservationInput
 *
 * Data for reserving a stream.
 */
export type ReserveRequestData = {
  /**
   * Event
   *
   * Identifier of the event to reserve the stream for.
   */
  event: string;
  format?: Format;
  /**
   * Record
   *
   * Whether to record the stream.
   */
  record?: boolean;
  /**
   * Metadata
   *
   * Metadata to attach to the stream.
   */
  metadata?: {
    [key: string]: string;
  } | null;
};

/**
 * Format
 *
 * Audio format.
 */
export type Format = "ogg";

/**
 * Availability
 *
 * Availability of a stream.
 */
export type CheckResponseAvailability = {
  /**
   * Event
   *
   * Identifier of the event that is currently being streamed.
   */
  event: string | null;
  checkedAt: CheckModelsUtcDatetime;
};

export type CheckCheckRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/check";
};

export type CheckCheckResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: CheckResponseAvailability;
};

export type CheckCheckResponse = CheckCheckResponses[keyof CheckCheckResponses];

export type PingPingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingPingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingPingResponse = PingPingResponses[keyof PingPingResponses];

export type PingHeadpingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingHeadpingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingHeadpingResponse =
  PingHeadpingResponses[keyof PingHeadpingResponses];

export type ReserveReserveRequest = {
  body: ReserveRequestData;
  path?: never;
  query?: never;
  url: "/reserve";
};

export type ReserveReserveErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Conflict Exception
   */
  409: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type ReserveReserveError =
  ReserveReserveErrors[keyof ReserveReserveErrors];

export type ReserveReserveResponses = {
  /**
   * Document created, URL follows
   */
  201: ReserveResponseReservation;
};

export type ReserveReserveResponse =
  ReserveReserveResponses[keyof ReserveReserveResponses];

export type SseSubscribeRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Types of events to subscribe to.
     */
    types?: SubscribeRequestTypes | string | null;
  };
  url: "/sse";
};

export type SseSubscribeErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type SseSubscribeError = SseSubscribeErrors[keyof SseSubscribeErrors];

export type SseSubscribeResponses = {
  /**
   * Request fulfilled, stream of Server-Sent Events follows
   */
  200: string;
};

export type SseSubscribeResponse =
  SseSubscribeResponses[keyof SseSubscribeResponses];

export type TestTestRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Parameters for testing.
     */
    parameters?: TestRequestParameters | string | null;
  };
  url: "/test";
};

export type TestTestErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TestTestError = TestTestErrors[keyof TestTestErrors];

export type TestTestResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: TestResponseResult;
};

export type TestTestResponse = TestTestResponses[keyof TestTestResponses];
