// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * EventType
 *
 * Event types.
 */
export const SseModelsEventTypeSchema = z
  .enum(["test"])
  .register(z.globalRegistry, {
    description: "Event types.",
  });

/**
 * _Event_type_OrderByInput
 */
export const ShowsModelsEventTypeOrderByInputSchema = z.object({
  type: z.enum(["asc", "desc"]),
});

/**
 * _Event_showId_OrderByInput
 */
export const ShowsModelsEventShowIdOrderByInputSchema = z.object({
  showId: z.enum(["asc", "desc"]),
});

/**
 * _Event_id_OrderByInput
 */
export const ShowsModelsEventIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

/**
 * _Event_RelevanceInner
 */
export const ShowsModelsEventRelevanceInnerSchema = z.object({
  fields: z.array(z.enum(["id", "type", "showId"])),
  search: z.string(),
  sort: z.enum(["asc", "desc"]),
});

/**
 * _Event_RelevanceOrderByInput
 */
export const ShowsModelsEventRelevanceOrderByInputSchema = z.object({
  _relevance: ShowsModelsEventRelevanceInnerSchema,
});

/**
 * _EventWhereUnique_id_Input
 */
export const ShowsModelsEventWhereUniqueIdInputSchema = z.object({
  id: z.string(),
});

export const ShowsModelsYeardaySchema = z.union([
  z.int().gte(-366).lte(-1),
  z.int().gte(1).lte(366),
]);

export const ShowsModelsWeekSchema = z.union([
  z.int().gte(-53).lte(-1),
  z.int().gte(1).lte(53),
]);

/**
 * Weekday
 *
 * Weekday options.
 */
export const ShowsModelsWeekdaySchema = z
  .enum([
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
  ])
  .register(z.globalRegistry, {
    description: "Weekday options.",
  });

/**
 * WeekdayRule
 *
 * Day rule data.
 */
export const ShowsModelsWeekdayRuleSchema = z
  .object({
    day: ShowsModelsWeekdaySchema,
    occurrence: ShowsModelsWeekSchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Day rule data.",
  });

/**
 * EventType
 */
export const ShowsModelsEventTypeSchema = z.enum([
  "live",
  "replay",
  "prerecorded",
]);

/**
 * StringFilter
 */
export const ShowsModelsStringFilterSchema = z.object({
  equals: z.string().optional(),
  notIn: z.array(z.string()).optional(),
  lt: z.string().optional(),
  lte: z.string().optional(),
  gt: z.string().optional(),
  gte: z.string().optional(),
  contains: z.string().optional(),
  startswith: z.string().optional(),
  endswith: z.string().optional(),
  in: z.array(z.string()).optional(),
  get not() {
    return z.union([z.string(), ShowsModelsStringFilterSchema]).optional();
  },
  mode: z.enum(["default", "insensitive"]).optional(),
  search: z.string().optional(),
});

export const ShowsModelsUpdateRequestIdSchema = z.uuid();

/**
 * ShowUpdateManyMutationInput
 *
 * Arguments for updating many records
 */
export const ShowsModelsUpdateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    title: z.string().optional(),
    description: z.string().nullish(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for updating many records",
  });

/**
 * Datetime without timezone.
 */
export const ShowsModelsNaiveDatetimeSchema = z.iso
  .datetime({ offset: true, local: true })
  .register(z.globalRegistry, {
    description: "Datetime without timezone.",
  });

/**
 * UntilTermination
 *
 * Until termination data.
 */
export const ShowsModelsUntilTerminationSchema = z
  .object({
    type: z
      .literal("until")
      .register(z.globalRegistry, {
        description: "Type of the termination.",
      })
      .optional()
      .default("until"),
    until: ShowsModelsNaiveDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Until termination data.",
  });

/**
 * Timezone name.
 */
export const ShowsModelsTimezoneSchema = z.string().register(z.globalRegistry, {
  description: "Timezone name.",
});

/**
 * Duration of time.
 */
export const ShowsModelsTimedeltaSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Duration of time.",
  });

/**
 * CountTermination
 *
 * Count termination data.
 */
export const ShowsModelsCountTerminationSchema = z
  .object({
    type: z
      .literal("count")
      .register(z.globalRegistry, {
        description: "Type of the termination.",
      })
      .optional()
      .default("count"),
    count: z.int().gt(0).register(z.globalRegistry, {
      description: "Number of instances of recurring event.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Count termination data.",
  });

export const ShowsModelsTerminationSchema = z.union([
  ShowsModelsCountTerminationSchema,
  ShowsModelsUntilTerminationSchema,
]);

/**
 * Exclusion
 *
 * Exclusion data.
 */
export const ShowsModelsExclusionSchema = z
  .object({
    start: ShowsModelsNaiveDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Exclusion data.",
  });

/**
 * Inclusion
 *
 * Inclusion data.
 */
export const ShowsModelsInclusionSchema = z
  .object({
    start: ShowsModelsNaiveDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Inclusion data.",
  });

export const ShowsModelsMonthSchema = z.int().gte(1).lte(12);

export const ShowsModelsMonthdaySchema = z.union([
  z.int().gte(-31).lte(-1),
  z.int().gte(1).lte(31),
]);

export const ShowsModelsHourSchema = z.int().gte(0).lte(23);

export const ShowsModelsMinuteSchema = z.int().gte(0).lte(59);

export const ShowsModelsSecondSchema = z.int().gte(0).lte(59);

/**
 * Frequency
 *
 * Frequency options.
 */
export const ShowsModelsFrequencySchema = z
  .enum([
    "secondly",
    "minutely",
    "hourly",
    "daily",
    "weekly",
    "monthly",
    "yearly",
  ])
  .register(z.globalRegistry, {
    description: "Frequency options.",
  });

/**
 * Recurrence
 *
 * Recurrence rule data.
 */
export const ShowsModelsRecurrenceSchema = z
  .object({
    frequency: ShowsModelsFrequencySchema,
    termination: ShowsModelsTerminationSchema.nullish().default(null),
    interval: z.int().gt(0).nullish().default(null),
    bySeconds: z.array(ShowsModelsSecondSchema).nullish().default(null),
    byMinutes: z.array(ShowsModelsMinuteSchema).nullish().default(null),
    byHours: z.array(ShowsModelsHourSchema).nullish().default(null),
    byWeekdays: z.array(ShowsModelsWeekdayRuleSchema).nullish().default(null),
    byMonthdays: z.array(ShowsModelsMonthdaySchema).nullish().default(null),
    byYeardays: z.array(ShowsModelsYeardaySchema).nullish().default(null),
    byWeeks: z.array(ShowsModelsWeekSchema).nullish().default(null),
    byMonths: z.array(ShowsModelsMonthSchema).nullish().default(null),
    bySetPositions: z.array(ShowsModelsYeardaySchema).nullish().default(null),
    weekStart: ShowsModelsWeekdaySchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Recurrence rule data.",
  });

/**
 * _Show_description_OrderByInput
 */
export const ShowDescriptionOrderByInputSchema = z.object({
  description: z.enum(["asc", "desc"]),
});

/**
 * _Show_title_OrderByInput
 */
export const ShowTitleOrderByInputSchema = z.object({
  title: z.enum(["asc", "desc"]),
});

/**
 * _Show_id_OrderByInput
 */
export const ShowIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

export const ShowOrderByInputSchema = z.union([
  ShowIdOrderByInputSchema,
  ShowTitleOrderByInputSchema,
  ShowDescriptionOrderByInputSchema,
]);

export const ShowsModelsListRequestOrderSchema = z
  .union([ShowOrderByInputSchema, z.array(ShowOrderByInputSchema)])
  .nullable();

export const ShowsModelsListRequestOffsetSchema = z.int().nullable();

export const ShowsModelsListRequestLimitSchema = z.int().nullable();

export const ShowsModelsGetRequestIdSchema = z.uuid();

export const ShowsModelsDeleteRequestIdSchema = z.uuid();

/**
 * ShowCreateWithoutRelationsInput
 *
 * Required arguments to the Show create method, without relations
 */
export const ShowsModelsCreateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    description: z.string().nullish(),
    title: z.string(),
  })
  .register(z.globalRegistry, {
    description:
      "Required arguments to the Show create method, without relations",
  });

/**
 * _Event_type_OrderByInput
 */
export const InstancesModelsEventTypeOrderByInputSchema = z.object({
  type: z.enum(["asc", "desc"]),
});

/**
 * _Event_showId_OrderByInput
 */
export const InstancesModelsEventShowIdOrderByInputSchema = z.object({
  showId: z.enum(["asc", "desc"]),
});

/**
 * _Event_id_OrderByInput
 */
export const InstancesModelsEventIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

/**
 * _Event_RelevanceInner
 */
export const InstancesModelsEventRelevanceInnerSchema = z.object({
  fields: z.array(z.enum(["id", "type", "showId"])),
  search: z.string(),
  sort: z.enum(["asc", "desc"]),
});

/**
 * _Event_RelevanceOrderByInput
 */
export const InstancesModelsEventRelevanceOrderByInputSchema = z.object({
  _relevance: InstancesModelsEventRelevanceInnerSchema,
});

/**
 * _EventWhereUnique_id_Input
 */
export const InstancesModelsEventWhereUniqueIdInputSchema = z.object({
  id: z.string(),
});

export const InstancesModelsYeardaySchema = z.union([
  z.int().gte(-366).lte(-1),
  z.int().gte(1).lte(366),
]);

export const InstancesModelsWeekSchema = z.union([
  z.int().gte(-53).lte(-1),
  z.int().gte(1).lte(53),
]);

/**
 * Weekday
 *
 * Weekday options.
 */
export const InstancesModelsWeekdaySchema = z
  .enum([
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
  ])
  .register(z.globalRegistry, {
    description: "Weekday options.",
  });

/**
 * WeekdayRule
 *
 * Day rule data.
 */
export const InstancesModelsWeekdayRuleSchema = z
  .object({
    day: InstancesModelsWeekdaySchema,
    occurrence: InstancesModelsWeekSchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Day rule data.",
  });

/**
 * StringFilter
 */
export const InstancesModelsStringFilterSchema = z.object({
  equals: z.string().optional(),
  notIn: z.array(z.string()).optional(),
  lt: z.string().optional(),
  lte: z.string().optional(),
  gt: z.string().optional(),
  gte: z.string().optional(),
  contains: z.string().optional(),
  startswith: z.string().optional(),
  endswith: z.string().optional(),
  in: z.array(z.string()).optional(),
  get not() {
    return z.union([z.string(), InstancesModelsStringFilterSchema]).optional();
  },
  mode: z.enum(["default", "insensitive"]).optional(),
  search: z.string().optional(),
});

/**
 * EventType
 */
export const InstancesModelsEventTypeSchema = z.enum([
  "live",
  "replay",
  "prerecorded",
]);

/**
 * Datetime without timezone.
 */
export const InstancesModelsNaiveDatetimeSchema = z.iso
  .datetime({ offset: true, local: true })
  .register(z.globalRegistry, {
    description: "Datetime without timezone.",
  });

/**
 * InstanceUpdateInput
 *
 * Data to update an instance.
 */
export const InstancesModelsUpdateRequestDataSchema = z
  .object({
    start: InstancesModelsNaiveDatetimeSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Data to update an instance.",
  });

/**
 * UntilTermination
 *
 * Until termination data.
 */
export const InstancesModelsUntilTerminationSchema = z
  .object({
    type: z
      .literal("until")
      .register(z.globalRegistry, {
        description: "Type of the termination.",
      })
      .optional()
      .default("until"),
    until: InstancesModelsNaiveDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Until termination data.",
  });

/**
 * Datetime in UTC.
 */
export const InstancesModelsUtcDatetimeSchema = z.iso
  .datetime({ offset: true, local: true })
  .register(z.globalRegistry, {
    description: "Datetime in UTC.",
  });

/**
 * Timezone name.
 */
export const InstancesModelsTimezoneSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Timezone name.",
  });

/**
 * Duration of time.
 */
export const InstancesModelsTimedeltaSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Duration of time.",
  });

/**
 * CountTermination
 *
 * Count termination data.
 */
export const InstancesModelsCountTerminationSchema = z
  .object({
    type: z
      .literal("count")
      .register(z.globalRegistry, {
        description: "Type of the termination.",
      })
      .optional()
      .default("count"),
    count: z.int().gt(0).register(z.globalRegistry, {
      description: "Number of instances of recurring event.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Count termination data.",
  });

export const InstancesModelsTerminationSchema = z.union([
  InstancesModelsCountTerminationSchema,
  InstancesModelsUntilTerminationSchema,
]);

/**
 * Exclusion
 *
 * Exclusion data.
 */
export const InstancesModelsExclusionSchema = z
  .object({
    start: InstancesModelsNaiveDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Exclusion data.",
  });

/**
 * Inclusion
 *
 * Inclusion data.
 */
export const InstancesModelsInclusionSchema = z
  .object({
    start: InstancesModelsNaiveDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Inclusion data.",
  });

export const InstancesModelsMonthSchema = z.int().gte(1).lte(12);

export const InstancesModelsMonthdaySchema = z.union([
  z.int().gte(-31).lte(-1),
  z.int().gte(1).lte(31),
]);

export const InstancesModelsHourSchema = z.int().gte(0).lte(23);

export const InstancesModelsMinuteSchema = z.int().gte(0).lte(59);

export const InstancesModelsSecondSchema = z.int().gte(0).lte(59);

/**
 * Frequency
 *
 * Frequency options.
 */
export const InstancesModelsFrequencySchema = z
  .enum([
    "secondly",
    "minutely",
    "hourly",
    "daily",
    "weekly",
    "monthly",
    "yearly",
  ])
  .register(z.globalRegistry, {
    description: "Frequency options.",
  });

/**
 * Recurrence
 *
 * Recurrence rule data.
 */
export const InstancesModelsRecurrenceSchema = z
  .object({
    frequency: InstancesModelsFrequencySchema,
    termination: InstancesModelsTerminationSchema.nullish().default(null),
    interval: z.int().gt(0).nullish().default(null),
    bySeconds: z.array(InstancesModelsSecondSchema).nullish().default(null),
    byMinutes: z.array(InstancesModelsMinuteSchema).nullish().default(null),
    byHours: z.array(InstancesModelsHourSchema).nullish().default(null),
    byWeekdays: z
      .array(InstancesModelsWeekdayRuleSchema)
      .nullish()
      .default(null),
    byMonthdays: z.array(InstancesModelsMonthdaySchema).nullish().default(null),
    byYeardays: z.array(InstancesModelsYeardaySchema).nullish().default(null),
    byWeeks: z.array(InstancesModelsWeekSchema).nullish().default(null),
    byMonths: z.array(InstancesModelsMonthSchema).nullish().default(null),
    bySetPositions: z
      .array(InstancesModelsYeardaySchema)
      .nullish()
      .default(null),
    weekStart: InstancesModelsWeekdaySchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Recurrence rule data.",
  });

export const SortOrderSchema = z.enum(["asc", "desc"]);

/**
 * InstanceOrderByEventIdInput
 *
 * Order by event ID of the instance.
 */
export const InstanceOrderByEventIdInputSchema = z
  .object({
    eventId: SortOrderSchema,
  })
  .register(z.globalRegistry, {
    description: "Order by event ID of the instance.",
  });

/**
 * InstanceOrderByDurationInput
 *
 * Order by duration of the instance.
 */
export const InstanceOrderByDurationInputSchema = z
  .object({
    duration: SortOrderSchema,
  })
  .register(z.globalRegistry, {
    description: "Order by duration of the instance.",
  });

/**
 * InstanceOrderByStartInput
 *
 * Order by start datetime of the instance.
 */
export const InstanceOrderByStartInputSchema = z
  .object({
    start: SortOrderSchema,
  })
  .register(z.globalRegistry, {
    description: "Order by start datetime of the instance.",
  });

export const InstanceOrderByInputSchema = z.union([
  InstanceOrderByStartInputSchema,
  InstanceOrderByDurationInputSchema,
  InstanceOrderByEventIdInputSchema,
]);

export const InstancesModelsListRequestOrderSchema = z
  .union([InstanceOrderByInputSchema, z.array(InstanceOrderByInputSchema)])
  .nullable();

/**
 * InstanceCreateInput
 *
 * Data to create an instance.
 */
export const InstancesModelsCreateRequestDataSchema = z
  .object({
    start: InstancesModelsNaiveDatetimeSchema,
    eventId: z.string().register(z.globalRegistry, {
      description: "Identifier of the event the instance belongs to.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Data to create an instance.",
  });

/**
 * _Event_type_OrderByInput
 */
export const EventsModelsEventTypeOrderByInputSchema = z.object({
  type: z.enum(["asc", "desc"]),
});

/**
 * _Event_showId_OrderByInput
 */
export const EventsModelsEventShowIdOrderByInputSchema = z.object({
  showId: z.enum(["asc", "desc"]),
});

/**
 * _Event_id_OrderByInput
 */
export const EventsModelsEventIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

/**
 * _Event_RelevanceInner
 */
export const EventsModelsEventRelevanceInnerSchema = z.object({
  fields: z.array(z.enum(["id", "type", "showId"])),
  search: z.string(),
  sort: z.enum(["asc", "desc"]),
});

/**
 * _Event_RelevanceOrderByInput
 */
export const EventsModelsEventRelevanceOrderByInputSchema = z.object({
  _relevance: EventsModelsEventRelevanceInnerSchema,
});

/**
 * _EventWhereUnique_id_Input
 */
export const EventsModelsEventWhereUniqueIdInputSchema = z.object({
  id: z.string(),
});

export const EventsModelsYeardaySchema = z.union([
  z.int().gte(-366).lte(-1),
  z.int().gte(1).lte(366),
]);

export const EventsModelsWeekSchema = z.union([
  z.int().gte(-53).lte(-1),
  z.int().gte(1).lte(53),
]);

/**
 * Weekday
 *
 * Weekday options.
 */
export const EventsModelsWeekdaySchema = z
  .enum([
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
  ])
  .register(z.globalRegistry, {
    description: "Weekday options.",
  });

/**
 * WeekdayRule
 *
 * Day rule data.
 */
export const EventsModelsWeekdayRuleSchema = z
  .object({
    day: EventsModelsWeekdaySchema,
    occurrence: EventsModelsWeekSchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Day rule data.",
  });

/**
 * StringFilter
 */
export const EventsModelsStringFilterSchema = z.object({
  equals: z.string().optional(),
  notIn: z.array(z.string()).optional(),
  lt: z.string().optional(),
  lte: z.string().optional(),
  gt: z.string().optional(),
  gte: z.string().optional(),
  contains: z.string().optional(),
  startswith: z.string().optional(),
  endswith: z.string().optional(),
  in: z.array(z.string()).optional(),
  get not() {
    return z.union([z.string(), EventsModelsStringFilterSchema]).optional();
  },
  mode: z.enum(["default", "insensitive"]).optional(),
  search: z.string().optional(),
});

/**
 * EventType
 */
export const EventsModelsEventTypeSchema = z.enum([
  "live",
  "replay",
  "prerecorded",
]);

export const EventsModelsUpdateRequestIdSchema = z.uuid();

/**
 * Datetime without timezone.
 */
export const EventsModelsNaiveDatetimeSchema = z.iso
  .datetime({ offset: true, local: true })
  .register(z.globalRegistry, {
    description: "Datetime without timezone.",
  });

/**
 * Exclusion
 *
 * Exclusion data.
 */
export const EventsModelsExclusionSchema = z
  .object({
    start: EventsModelsNaiveDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Exclusion data.",
  });

/**
 * Inclusion
 *
 * Inclusion data.
 */
export const EventsModelsInclusionSchema = z
  .object({
    start: EventsModelsNaiveDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Inclusion data.",
  });

export const EventsModelsMonthSchema = z.int().gte(1).lte(12);

export const EventsModelsMonthdaySchema = z.union([
  z.int().gte(-31).lte(-1),
  z.int().gte(1).lte(31),
]);

export const EventsModelsHourSchema = z.int().gte(0).lte(23);

export const EventsModelsMinuteSchema = z.int().gte(0).lte(59);

export const EventsModelsSecondSchema = z.int().gte(0).lte(59);

/**
 * UntilTermination
 *
 * Until termination data.
 */
export const EventsModelsUntilTerminationSchema = z
  .object({
    type: z
      .literal("until")
      .register(z.globalRegistry, {
        description: "Type of the termination.",
      })
      .optional()
      .default("until"),
    until: EventsModelsNaiveDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Until termination data.",
  });

/**
 * CountTermination
 *
 * Count termination data.
 */
export const EventsModelsCountTerminationSchema = z
  .object({
    type: z
      .literal("count")
      .register(z.globalRegistry, {
        description: "Type of the termination.",
      })
      .optional()
      .default("count"),
    count: z.int().gt(0).register(z.globalRegistry, {
      description: "Number of instances of recurring event.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Count termination data.",
  });

export const EventsModelsTerminationSchema = z.union([
  EventsModelsCountTerminationSchema,
  EventsModelsUntilTerminationSchema,
]);

/**
 * Frequency
 *
 * Frequency options.
 */
export const EventsModelsFrequencySchema = z
  .enum([
    "secondly",
    "minutely",
    "hourly",
    "daily",
    "weekly",
    "monthly",
    "yearly",
  ])
  .register(z.globalRegistry, {
    description: "Frequency options.",
  });

/**
 * RecurrenceUpdateInput
 *
 * Data to update a recurrence rule.
 */
export const RecurrenceUpdateInputSchema = z
  .object({
    frequency: EventsModelsFrequencySchema.optional(),
    termination: EventsModelsTerminationSchema.nullish(),
    interval: z.int().gt(0).nullish(),
    bySeconds: z.array(EventsModelsSecondSchema).nullish(),
    byMinutes: z.array(EventsModelsMinuteSchema).nullish(),
    byHours: z.array(EventsModelsHourSchema).nullish(),
    byWeekdays: z.array(EventsModelsWeekdayRuleSchema).nullish(),
    byMonthdays: z.array(EventsModelsMonthdaySchema).nullish(),
    byYeardays: z.array(EventsModelsYeardaySchema).nullish(),
    byWeeks: z.array(EventsModelsWeekSchema).nullish(),
    byMonths: z.array(EventsModelsMonthSchema).nullish(),
    bySetPositions: z.array(EventsModelsYeardaySchema).nullish(),
    weekStart: EventsModelsWeekdaySchema.nullish(),
  })
  .register(z.globalRegistry, {
    description: "Data to update a recurrence rule.",
  });

/**
 * Timezone name.
 */
export const EventsModelsTimezoneSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Timezone name.",
  });

/**
 * Duration of time.
 */
export const EventsModelsTimedeltaSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Duration of time.",
  });

/**
 * EventUpdateInput
 *
 * Data to update an event.
 */
export const EventsModelsUpdateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    type: EventsModelsEventTypeSchema.optional(),
    start: EventsModelsNaiveDatetimeSchema.optional(),
    duration: EventsModelsTimedeltaSchema.optional(),
    timezone: EventsModelsTimezoneSchema.optional(),
    recurrence: RecurrenceUpdateInputSchema.nullish(),
    include: z.array(EventsModelsInclusionSchema).nullish(),
    exclude: z.array(EventsModelsExclusionSchema).nullish(),
  })
  .register(z.globalRegistry, {
    description: "Data to update an event.",
  });

/**
 * Datetime in UTC.
 */
export const EventsModelsUtcDatetimeSchema = z.iso
  .datetime({ offset: true, local: true })
  .register(z.globalRegistry, {
    description: "Datetime in UTC.",
  });

/**
 * Recurrence
 *
 * Recurrence rule data.
 */
export const EventsModelsRecurrenceSchema = z
  .object({
    frequency: EventsModelsFrequencySchema,
    termination: EventsModelsTerminationSchema.nullish().default(null),
    interval: z.int().gt(0).nullish().default(null),
    bySeconds: z.array(EventsModelsSecondSchema).nullish().default(null),
    byMinutes: z.array(EventsModelsMinuteSchema).nullish().default(null),
    byHours: z.array(EventsModelsHourSchema).nullish().default(null),
    byWeekdays: z.array(EventsModelsWeekdayRuleSchema).nullish().default(null),
    byMonthdays: z.array(EventsModelsMonthdaySchema).nullish().default(null),
    byYeardays: z.array(EventsModelsYeardaySchema).nullish().default(null),
    byWeeks: z.array(EventsModelsWeekSchema).nullish().default(null),
    byMonths: z.array(EventsModelsMonthSchema).nullish().default(null),
    bySetPositions: z.array(EventsModelsYeardaySchema).nullish().default(null),
    weekStart: EventsModelsWeekdaySchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Recurrence rule data.",
  });

export const EventOrderByInputSchema = z.union([
  EventsModelsEventIdOrderByInputSchema,
  EventsModelsEventTypeOrderByInputSchema,
  EventsModelsEventShowIdOrderByInputSchema,
]);

export const EventsModelsListRequestOrderSchema = z
  .union([EventOrderByInputSchema, z.array(EventOrderByInputSchema)])
  .nullable();

export const EventsModelsListRequestOffsetSchema = z.int().nullable();

export const EventsModelsListRequestLimitSchema = z.int().nullable();

export const EventsModelsGetRequestIdSchema = z.uuid();

export const EventsModelsDeleteRequestIdSchema = z.uuid();

/**
 * EventCreateInput
 *
 * Data to create an event.
 */
export const EventsModelsCreateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    showId: z.string().nullish(),
    type: EventsModelsEventTypeSchema,
    start: EventsModelsNaiveDatetimeSchema,
    duration: EventsModelsTimedeltaSchema,
    timezone: EventsModelsTimezoneSchema,
    recurrence: EventsModelsRecurrenceSchema.nullish(),
    include: z.array(EventsModelsInclusionSchema).nullish(),
    exclude: z.array(EventsModelsExclusionSchema).nullish(),
  })
  .register(z.globalRegistry, {
    description: "Data to create an event.",
  });

/**
 * Datetime without timezone.
 */
export const UpdateRequestStartSchema = z.iso
  .datetime({ offset: true, local: true })
  .register(z.globalRegistry, {
    description: "Datetime without timezone.",
  });

export const UpdateRequestEventIdSchema = z.uuid();

/**
 * TimeRangeQuery
 *
 * Query for events in a time range.
 */
export const TimeRangeQuerySchema = z
  .object({
    type: z
      .literal("time-range")
      .register(z.globalRegistry, {
        description: "Type of the query.",
      })
      .optional()
      .default("time-range"),
    start: EventsModelsUtcDatetimeSchema.nullish().default(null),
    end: EventsModelsUtcDatetimeSchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Query for events in a time range.",
  });

/**
 * Result
 *
 * Result of the test.
 */
export const TestResponseResultSchema = z
  .object({
    success: z.boolean().register(z.globalRegistry, {
      description: "Indicates if the test was successful.",
    }),
    message: z.string().register(z.globalRegistry, {
      description: "Message returned from the test.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Result of the test.",
  });

/**
 * Parameters
 *
 * Parameters for testing.
 */
export const ParametersSchema = z
  .object({
    message: z.string().nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Parameters for testing.",
  });

export const TestRequestParametersSchema = ParametersSchema.nullable();

export const SubscribeRequestTypesSchema = z
  .union([z.string(), z.array(SseModelsEventTypeSchema)])
  .nullable();

export const SplitRequestIdSchema = z.uuid();

/**
 * EventUpdateInput
 *
 * Data to update an event.
 */
export const EventUpdateInputSchema = z
  .object({
    id: z.string().optional(),
    type: EventsModelsEventTypeSchema.optional(),
    start: EventsModelsNaiveDatetimeSchema.optional(),
    duration: EventsModelsTimedeltaSchema.optional(),
    timezone: EventsModelsTimezoneSchema.optional(),
    recurrence: RecurrenceUpdateInputSchema.nullish(),
    include: z.array(EventsModelsInclusionSchema).nullish(),
    exclude: z.array(EventsModelsExclusionSchema).nullish(),
  })
  .register(z.globalRegistry, {
    description: "Data to update an event.",
  });

/**
 * EventSplitInput
 *
 * Data to split an event.
 */
export const SplitRequestDataSchema = z
  .object({
    at: EventsModelsNaiveDatetimeSchema,
    update: EventUpdateInputSchema.nullish(),
  })
  .register(z.globalRegistry, {
    description: "Data to split an event.",
  });

/**
 * RecurringQuery
 *
 * Query for recurring events.
 */
export const RecurringQuerySchema = z
  .object({
    type: z
      .literal("recurring")
      .register(z.globalRegistry, {
        description: "Type of the query.",
      })
      .optional()
      .default("recurring"),
    recurring: z.boolean().register(z.globalRegistry, {
      description: "Whether to search for recurring or non-recurring events.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Query for recurring events.",
  });

export const QuerySchema = z.union([
  z
    .object({
      type: z.literal("TimeRangeQuery"),
    })
    .and(TimeRangeQuerySchema),
  z
    .object({
      type: z.literal("RecurringQuery"),
    })
    .and(RecurringQuerySchema),
]);

/**
 * Datetime in UTC.
 */
export const ListRequestStartSchema = z.iso
  .datetime({ offset: true, local: true })
  .register(z.globalRegistry, {
    description: "Datetime in UTC.",
  });

export const ListRequestQuerySchema = QuerySchema.nullable();

/**
 * Datetime in UTC.
 */
export const ListRequestEndSchema = z.iso
  .datetime({ offset: true, local: true })
  .register(z.globalRegistry, {
    description: "Datetime in UTC.",
  });

/**
 * Datetime without timezone.
 */
export const GetRequestStartSchema = z.iso
  .datetime({ offset: true, local: true })
  .register(z.globalRegistry, {
    description: "Datetime without timezone.",
  });

export const GetRequestEventIdSchema = z.uuid();

/**
 * Datetime without timezone.
 */
export const DeleteRequestStartSchema = z.iso
  .datetime({ offset: true, local: true })
  .register(z.globalRegistry, {
    description: "Datetime without timezone.",
  });

export const DeleteRequestEventIdSchema = z.uuid();

export const ShowsModelsUpdateRequestIncludeSchema = z
  .lazy(() => ShowIncludeSchema)
  .nullable();

/**
 * ShowIncludeFromShow
 *
 * Relational arguments for Show
 */
export const ShowsModelsShowIncludeFromShowSchema = z
  .object({
    events: z
      .union([
        z.boolean(),
        z.lazy((): any => ShowsModelsFindManyEventArgsFromShowSchema),
      ])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Show",
  });

/**
 * FindManyEventArgsFromShow
 *
 * Arguments for Show
 */
export const ShowsModelsFindManyEventArgsFromShowSchema = z
  .object({
    take: z.int().optional(),
    skip: z.int().optional(),
    orderBy: z
      .union([
        ShowsModelsEventIdOrderByInputSchema,
        ShowsModelsEventTypeOrderByInputSchema,
        ShowsModelsEventShowIdOrderByInputSchema,
        ShowsModelsEventRelevanceOrderByInputSchema,
        z.array(
          z.union([
            ShowsModelsEventIdOrderByInputSchema,
            ShowsModelsEventTypeOrderByInputSchema,
            ShowsModelsEventShowIdOrderByInputSchema,
            ShowsModelsEventRelevanceOrderByInputSchema,
          ]),
        ),
      ])
      .optional(),
    where: z.lazy((): any => ShowsModelsEventWhereInputSchema).optional(),
    cursor: ShowsModelsEventWhereUniqueIdInputSchema.optional(),
    distinct: z.array(z.enum(["id", "type", "showId"])).optional(),
    include: z
      .lazy((): any => ShowsModelsEventIncludeFromEventSchema)
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Show",
  });

/**
 * ShowArgsFromEvent
 *
 * Arguments for Event
 */
export const ShowsModelsShowArgsFromEventSchema = z
  .object({
    include: ShowsModelsShowIncludeFromShowSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Event",
  });

/**
 * EventIncludeFromEvent
 *
 * Relational arguments for Event
 */
export const ShowsModelsEventIncludeFromEventSchema = z
  .object({
    show: z.union([z.boolean(), ShowsModelsShowArgsFromEventSchema]).optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Event",
  });

/**
 * ShowWhereInput
 *
 * Show arguments for searching
 */
export const ShowsModelsShowWhereInputSchema = z
  .object({
    id: z.union([z.string(), ShowsModelsStringFilterSchema]).optional(),
    title: z.union([z.string(), ShowsModelsStringFilterSchema]).optional(),
    description: z.union([z.string(), ShowsModelsStringFilterSchema]).nullish(),
    events: z
      .lazy((): any => ShowsModelsEventListRelationFilterSchema)
      .optional(),
    and: z.array(z.lazy((): any => ShowsModelsShowWhereInputSchema)).optional(),
    or: z.array(z.lazy((): any => ShowsModelsShowWhereInputSchema)).optional(),
    not: z.array(z.lazy((): any => ShowsModelsShowWhereInputSchema)).optional(),
  })
  .register(z.globalRegistry, {
    description: "Show arguments for searching",
  });

/**
 * ShowRelationFilter
 */
export const ShowsModelsShowRelationFilterSchema = z.object({
  is: ShowsModelsShowWhereInputSchema.optional(),
  isNot: ShowsModelsShowWhereInputSchema.optional(),
});

/**
 * EventWhereInput
 *
 * Event arguments for searching
 */
export const ShowsModelsEventWhereInputSchema = z
  .object({
    id: z.union([z.string(), ShowsModelsStringFilterSchema]).optional(),
    type: ShowsModelsEventTypeSchema.optional(),
    showId: z.union([z.string(), ShowsModelsStringFilterSchema]).nullish(),
    show: ShowsModelsShowRelationFilterSchema.optional(),
    and: z
      .array(z.lazy((): any => ShowsModelsEventWhereInputSchema))
      .optional(),
    or: z.array(z.lazy((): any => ShowsModelsEventWhereInputSchema)).optional(),
    not: z
      .array(z.lazy((): any => ShowsModelsEventWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Event arguments for searching",
  });

/**
 * EventListRelationFilter
 */
export const ShowsModelsEventListRelationFilterSchema = z.object({
  some: ShowsModelsEventWhereInputSchema.optional(),
  none: ShowsModelsEventWhereInputSchema.optional(),
  every: ShowsModelsEventWhereInputSchema.optional(),
});

/**
 * ShowInclude
 *
 * Show relational arguments
 */
export const ShowIncludeSchema = z
  .object({
    events: z
      .union([z.boolean(), ShowsModelsFindManyEventArgsFromShowSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Show relational arguments",
  });

/**
 * Show
 *
 * Show data.
 */
export const ShowsModelsShowSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the show.",
    }),
    title: z.string().register(z.globalRegistry, {
      description: "Title of the show.",
    }),
    description: z.string().nullable(),
    events: z.array(z.lazy((): any => ShowsModelsEventSchema)).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Show data.",
  });

/**
 * Event
 *
 * Event data.
 */
export const ShowsModelsEventSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the event.",
    }),
    type: ShowsModelsEventTypeSchema,
    showId: z.uuid().nullable(),
    show: ShowsModelsShowSchema.nullable(),
    start: ShowsModelsNaiveDatetimeSchema,
    duration: ShowsModelsTimedeltaSchema,
    timezone: ShowsModelsTimezoneSchema,
    recurrence: ShowsModelsRecurrenceSchema.nullish().default(null),
    include: z.array(ShowsModelsInclusionSchema).nullish().default(null),
    exclude: z.array(ShowsModelsExclusionSchema).nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Event data.",
  });

/**
 * ShowList
 *
 * List of shows.
 */
export const ShowsModelsListResponseResultsSchema = z
  .object({
    count: z.int().register(z.globalRegistry, {
      description: "Total number of shows that matched the query.",
    }),
    limit: z.int().nullable(),
    offset: z.int().nullable(),
    shows: z.array(ShowsModelsShowSchema).register(z.globalRegistry, {
      description: "Shows that matched the request.",
    }),
  })
  .register(z.globalRegistry, {
    description: "List of shows.",
  });

export const ShowsModelsListRequestWhereSchema =
  ShowsModelsShowWhereInputSchema.nullable();

export const ShowsModelsListRequestIncludeSchema = ShowIncludeSchema.nullable();

export const ShowsModelsGetRequestIncludeSchema = ShowIncludeSchema.nullable();

export const ShowsModelsCreateRequestIncludeSchema =
  ShowIncludeSchema.nullable();

export const InstancesModelsUpdateRequestIncludeSchema = z
  .lazy(() => InstanceIncludeSchema)
  .nullable();

/**
 * EventIncludeFromEvent
 *
 * Relational arguments for Event
 */
export const InstancesModelsEventIncludeFromEventSchema = z
  .object({
    show: z
      .union([
        z.boolean(),
        z.lazy((): any => InstancesModelsShowArgsFromEventSchema),
      ])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Event",
  });

/**
 * ShowArgsFromEvent
 *
 * Arguments for Event
 */
export const InstancesModelsShowArgsFromEventSchema = z
  .object({
    include: z
      .lazy((): any => InstancesModelsShowIncludeFromShowSchema)
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Event",
  });

/**
 * EventListRelationFilter
 */
export const InstancesModelsEventListRelationFilterSchema = z.object({
  get some() {
    return InstancesModelsEventWhereInputSchema.optional();
  },
  get none() {
    return InstancesModelsEventWhereInputSchema.optional();
  },
  get every() {
    return InstancesModelsEventWhereInputSchema.optional();
  },
});

/**
 * EventWhereInput
 *
 * Event arguments for searching
 */
export const InstancesModelsEventWhereInputSchema = z
  .object({
    id: z.union([z.string(), InstancesModelsStringFilterSchema]).optional(),
    type: InstancesModelsEventTypeSchema.optional(),
    showId: z.union([z.string(), InstancesModelsStringFilterSchema]).nullish(),
    show: z.lazy((): any => InstancesModelsShowRelationFilterSchema).optional(),
    and: z
      .array(z.lazy((): any => InstancesModelsEventWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => InstancesModelsEventWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => InstancesModelsEventWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Event arguments for searching",
  });

/**
 * ShowWhereInput
 *
 * Show arguments for searching
 */
export const InstancesModelsShowWhereInputSchema = z
  .object({
    id: z.union([z.string(), InstancesModelsStringFilterSchema]).optional(),
    title: z.union([z.string(), InstancesModelsStringFilterSchema]).optional(),
    description: z
      .union([z.string(), InstancesModelsStringFilterSchema])
      .nullish(),
    events: InstancesModelsEventListRelationFilterSchema.optional(),
    and: z
      .array(z.lazy((): any => InstancesModelsShowWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => InstancesModelsShowWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => InstancesModelsShowWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Show arguments for searching",
  });

/**
 * ShowRelationFilter
 */
export const InstancesModelsShowRelationFilterSchema = z.object({
  is: InstancesModelsShowWhereInputSchema.optional(),
  isNot: InstancesModelsShowWhereInputSchema.optional(),
});

/**
 * FindManyEventArgsFromShow
 *
 * Arguments for Show
 */
export const InstancesModelsFindManyEventArgsFromShowSchema = z
  .object({
    take: z.int().optional(),
    skip: z.int().optional(),
    orderBy: z
      .union([
        InstancesModelsEventIdOrderByInputSchema,
        InstancesModelsEventTypeOrderByInputSchema,
        InstancesModelsEventShowIdOrderByInputSchema,
        InstancesModelsEventRelevanceOrderByInputSchema,
        z.array(
          z.union([
            InstancesModelsEventIdOrderByInputSchema,
            InstancesModelsEventTypeOrderByInputSchema,
            InstancesModelsEventShowIdOrderByInputSchema,
            InstancesModelsEventRelevanceOrderByInputSchema,
          ]),
        ),
      ])
      .optional(),
    where: InstancesModelsEventWhereInputSchema.optional(),
    cursor: InstancesModelsEventWhereUniqueIdInputSchema.optional(),
    distinct: z.array(z.enum(["id", "type", "showId"])).optional(),
    include: InstancesModelsEventIncludeFromEventSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Show",
  });

/**
 * ShowIncludeFromShow
 *
 * Relational arguments for Show
 */
export const InstancesModelsShowIncludeFromShowSchema = z
  .object({
    events: z
      .union([z.boolean(), InstancesModelsFindManyEventArgsFromShowSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Show",
  });

/**
 * EventInclude
 *
 * Event relational arguments
 */
export const InstancesModelsEventIncludeSchema = z
  .object({
    show: z
      .union([z.boolean(), InstancesModelsShowArgsFromEventSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Event relational arguments",
  });

/**
 * EventArgsFromInstance
 *
 * Event arguments to include when querying instances.
 */
export const EventArgsFromInstanceSchema = z
  .object({
    include: InstancesModelsEventIncludeSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Event arguments to include when querying instances.",
  });

/**
 * InstanceInclude
 *
 * Relations to include when querying instances.
 */
export const InstanceIncludeSchema = z
  .object({
    event: z.union([z.boolean(), EventArgsFromInstanceSchema]).optional(),
  })
  .register(z.globalRegistry, {
    description: "Relations to include when querying instances.",
  });

/**
 * Show
 *
 * Show data.
 */
export const InstancesModelsShowSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the show.",
    }),
    title: z.string().register(z.globalRegistry, {
      description: "Title of the show.",
    }),
    description: z.string().nullable(),
    events: z.array(z.lazy((): any => InstancesModelsEventSchema)).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Show data.",
  });

/**
 * Event
 *
 * Event data.
 */
export const InstancesModelsEventSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the event.",
    }),
    type: InstancesModelsEventTypeSchema,
    showId: z.uuid().nullable(),
    show: InstancesModelsShowSchema.nullable(),
    start: InstancesModelsNaiveDatetimeSchema,
    duration: InstancesModelsTimedeltaSchema,
    timezone: InstancesModelsTimezoneSchema,
    recurrence: InstancesModelsRecurrenceSchema.nullish().default(null),
    include: z.array(InstancesModelsInclusionSchema).nullish().default(null),
    exclude: z.array(InstancesModelsExclusionSchema).nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Event data.",
  });

/**
 * InstanceList
 *
 * List of instances.
 */
export const InstancesModelsListResponseResultsSchema = z
  .object({
    start: InstancesModelsUtcDatetimeSchema,
    end: InstancesModelsUtcDatetimeSchema,
    instances: z
      .array(z.lazy(() => InstanceSchema))
      .register(z.globalRegistry, {
        description: "Instances that matched the request.",
      }),
  })
  .register(z.globalRegistry, {
    description: "List of instances.",
  });

/**
 * Instance
 *
 * Instance data.
 */
export const InstanceSchema = z
  .object({
    start: InstancesModelsNaiveDatetimeSchema,
    duration: InstancesModelsTimedeltaSchema,
    eventId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the event the instance belongs to.",
    }),
    event: InstancesModelsEventSchema.nullable(),
  })
  .register(z.globalRegistry, {
    description: "Instance data.",
  });

export const InstancesModelsListRequestWhereSchema = z
  .lazy(() => InstanceWhereInputSchema)
  .nullable();

/**
 * EventRelationFilter
 */
export const EventRelationFilterSchema = z.object({
  is: InstancesModelsEventWhereInputSchema.optional(),
  isNot: InstancesModelsEventWhereInputSchema.optional(),
});

/**
 * InstanceWhereInput
 *
 * Instance arguments for searching.
 */
export const InstanceWhereInputSchema = z
  .object({
    event: EventRelationFilterSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Instance arguments for searching.",
  });

export const InstancesModelsListRequestIncludeSchema =
  InstanceIncludeSchema.nullable();

export const InstancesModelsGetRequestIncludeSchema =
  InstanceIncludeSchema.nullable();

export const InstancesModelsCreateRequestIncludeSchema =
  InstanceIncludeSchema.nullable();

export const EventsModelsUpdateRequestIncludeSchema = z
  .lazy(() => EventsModelsEventIncludeSchema)
  .nullable();

/**
 * EventIncludeFromEvent
 *
 * Relational arguments for Event
 */
export const EventsModelsEventIncludeFromEventSchema = z
  .object({
    show: z
      .union([
        z.boolean(),
        z.lazy((): any => EventsModelsShowArgsFromEventSchema),
      ])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Event",
  });

/**
 * ShowArgsFromEvent
 *
 * Arguments for Event
 */
export const EventsModelsShowArgsFromEventSchema = z
  .object({
    include: z
      .lazy((): any => EventsModelsShowIncludeFromShowSchema)
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Event",
  });

/**
 * EventListRelationFilter
 */
export const EventsModelsEventListRelationFilterSchema = z.object({
  get some() {
    return EventsModelsEventWhereInputSchema.optional();
  },
  get none() {
    return EventsModelsEventWhereInputSchema.optional();
  },
  get every() {
    return EventsModelsEventWhereInputSchema.optional();
  },
});

/**
 * EventWhereInput
 *
 * Event arguments for searching
 */
export const EventsModelsEventWhereInputSchema = z
  .object({
    id: z.union([z.string(), EventsModelsStringFilterSchema]).optional(),
    type: EventsModelsEventTypeSchema.optional(),
    showId: z.union([z.string(), EventsModelsStringFilterSchema]).nullish(),
    show: z.lazy((): any => EventsModelsShowRelationFilterSchema).optional(),
    and: z
      .array(z.lazy((): any => EventsModelsEventWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => EventsModelsEventWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => EventsModelsEventWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Event arguments for searching",
  });

/**
 * ShowWhereInput
 *
 * Show arguments for searching
 */
export const EventsModelsShowWhereInputSchema = z
  .object({
    id: z.union([z.string(), EventsModelsStringFilterSchema]).optional(),
    title: z.union([z.string(), EventsModelsStringFilterSchema]).optional(),
    description: z
      .union([z.string(), EventsModelsStringFilterSchema])
      .nullish(),
    events: EventsModelsEventListRelationFilterSchema.optional(),
    and: z
      .array(z.lazy((): any => EventsModelsShowWhereInputSchema))
      .optional(),
    or: z.array(z.lazy((): any => EventsModelsShowWhereInputSchema)).optional(),
    not: z
      .array(z.lazy((): any => EventsModelsShowWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Show arguments for searching",
  });

/**
 * ShowRelationFilter
 */
export const EventsModelsShowRelationFilterSchema = z.object({
  is: EventsModelsShowWhereInputSchema.optional(),
  isNot: EventsModelsShowWhereInputSchema.optional(),
});

/**
 * FindManyEventArgsFromShow
 *
 * Arguments for Show
 */
export const EventsModelsFindManyEventArgsFromShowSchema = z
  .object({
    take: z.int().optional(),
    skip: z.int().optional(),
    orderBy: z
      .union([
        EventsModelsEventIdOrderByInputSchema,
        EventsModelsEventTypeOrderByInputSchema,
        EventsModelsEventShowIdOrderByInputSchema,
        EventsModelsEventRelevanceOrderByInputSchema,
        z.array(
          z.union([
            EventsModelsEventIdOrderByInputSchema,
            EventsModelsEventTypeOrderByInputSchema,
            EventsModelsEventShowIdOrderByInputSchema,
            EventsModelsEventRelevanceOrderByInputSchema,
          ]),
        ),
      ])
      .optional(),
    where: EventsModelsEventWhereInputSchema.optional(),
    cursor: EventsModelsEventWhereUniqueIdInputSchema.optional(),
    distinct: z.array(z.enum(["id", "type", "showId"])).optional(),
    include: EventsModelsEventIncludeFromEventSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Show",
  });

/**
 * ShowIncludeFromShow
 *
 * Relational arguments for Show
 */
export const EventsModelsShowIncludeFromShowSchema = z
  .object({
    events: z
      .union([z.boolean(), EventsModelsFindManyEventArgsFromShowSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Show",
  });

/**
 * EventInclude
 *
 * Event relational arguments
 */
export const EventsModelsEventIncludeSchema = z
  .object({
    show: z
      .union([z.boolean(), EventsModelsShowArgsFromEventSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Event relational arguments",
  });

/**
 * Show
 *
 * Show data.
 */
export const EventsModelsShowSchema = z
  .object({
    id: z.string().register(z.globalRegistry, {
      description: "Identifier of the show.",
    }),
    title: z.string().register(z.globalRegistry, {
      description: "Title of the show.",
    }),
    description: z.string().nullable(),
    events: z.array(z.lazy((): any => EventsModelsEventSchema)).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Show data.",
  });

/**
 * Event
 *
 * Event data.
 */
export const EventsModelsEventSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the event.",
    }),
    type: EventsModelsEventTypeSchema,
    showId: z.uuid().nullable(),
    show: EventsModelsShowSchema.nullable(),
    start: EventsModelsNaiveDatetimeSchema,
    duration: EventsModelsTimedeltaSchema,
    timezone: EventsModelsTimezoneSchema,
    recurrence: EventsModelsRecurrenceSchema.nullish().default(null),
    include: z.array(EventsModelsInclusionSchema).nullish().default(null),
    exclude: z.array(EventsModelsExclusionSchema).nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Event data.",
  });

/**
 * EventList
 *
 * List of events.
 */
export const EventsModelsListResponseResultsSchema = z
  .object({
    count: z.int().register(z.globalRegistry, {
      description: "Total number of events that matched the query.",
    }),
    limit: z.int().nullable(),
    offset: z.int().nullable(),
    events: z.array(EventsModelsEventSchema).register(z.globalRegistry, {
      description: "Events that matched the request.",
    }),
  })
  .register(z.globalRegistry, {
    description: "List of events.",
  });

export const EventsModelsListRequestWhereSchema =
  EventsModelsEventWhereInputSchema.nullable();

export const EventsModelsListRequestIncludeSchema =
  EventsModelsEventIncludeSchema.nullable();

export const EventsModelsGetRequestIncludeSchema =
  EventsModelsEventIncludeSchema.nullable();

export const EventsModelsCreateRequestIncludeSchema =
  EventsModelsEventIncludeSchema.nullable();

/**
 * Instance
 *
 * Instance data.
 */
export const UpdateResponseInstanceSchema = z
  .object({
    start: InstancesModelsNaiveDatetimeSchema,
    duration: InstancesModelsTimedeltaSchema,
    eventId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the event the instance belongs to.",
    }),
    event: InstancesModelsEventSchema.nullable(),
  })
  .register(z.globalRegistry, {
    description: "Instance data.",
  });

/**
 * SplitResult
 *
 * Result of splitting an event.
 */
export const SplitResponseResultSchema = z
  .object({
    before: z.lazy((): any => GetResponseEventSchema),
    after: EventsModelsEventSchema,
  })
  .register(z.globalRegistry, {
    description: "Result of splitting an event.",
  });

/**
 * Event
 *
 * Event data.
 */
export const GetResponseEventSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the event.",
    }),
    type: EventsModelsEventTypeSchema,
    showId: z.uuid().nullable(),
    show: EventsModelsShowSchema.nullable(),
    start: EventsModelsNaiveDatetimeSchema,
    duration: EventsModelsTimedeltaSchema,
    timezone: EventsModelsTimezoneSchema,
    recurrence: EventsModelsRecurrenceSchema.nullish().default(null),
    include: z.array(EventsModelsInclusionSchema).nullish().default(null),
    exclude: z.array(EventsModelsExclusionSchema).nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Event data.",
  });

export const SplitRequestIncludeSchema =
  EventsModelsEventIncludeSchema.nullable();

/**
 * Show
 *
 * Show data.
 */
export const GetResponseShowSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the show.",
    }),
    title: z.string().register(z.globalRegistry, {
      description: "Title of the show.",
    }),
    description: z.string().nullable(),
    events: z.array(ShowsModelsEventSchema).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Show data.",
  });

export const GetResponseInstanceSchema = InstanceSchema.nullable();

/**
 * Instance
 *
 * Instance data.
 */
export const CreateResponseInstanceSchema = z
  .object({
    start: InstancesModelsNaiveDatetimeSchema,
    duration: InstancesModelsTimedeltaSchema,
    eventId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the event the instance belongs to.",
    }),
    event: InstancesModelsEventSchema.nullable(),
  })
  .register(z.globalRegistry, {
    description: "Instance data.",
  });

export const EventsIdDeleteRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: EventsModelsDeleteRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const EventsIdDeleteResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const InstancesEventidStartDeleteRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    eventId: DeleteRequestEventIdSchema,
    start: DeleteRequestStartSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const InstancesEventidStartDeleteResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const PingPingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingPingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const PingHeadpingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingHeadpingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const ShowsIdDeleteRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: ShowsModelsDeleteRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const ShowsIdDeleteResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const SseSubscribeRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      types: z.union([SubscribeRequestTypesSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, stream of Server-Sent Events follows
 */
export const SseSubscribeResponseSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Request fulfilled, stream of Server-Sent Events follows",
  });

export const TestTestRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      parameters: z.union([TestRequestParametersSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TestTestResponseSchema = TestResponseResultSchema;

export const EventsListRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      limit: z
        .union([EventsModelsListRequestLimitSchema, z.string()])
        .nullish(),
      offset: z
        .union([EventsModelsListRequestOffsetSchema, z.string()])
        .nullish(),
      where: z
        .union([EventsModelsListRequestWhereSchema, z.string()])
        .nullish(),
      query: z.union([ListRequestQuerySchema, z.string()]).nullish(),
      include: z
        .union([EventsModelsListRequestIncludeSchema, z.string()])
        .nullish(),
      order: z
        .union([EventsModelsListRequestOrderSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const EventsListResponseSchema = EventsModelsListResponseResultsSchema;

export const EventsCreateRequestSchema = z.object({
  body: EventsModelsCreateRequestDataSchema,
  path: z.never().optional(),
  query: z
    .object({
      include: z
        .union([EventsModelsCreateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Document created, URL follows
 */
export const EventsCreateResponseSchema = EventsModelsEventSchema;

export const EventsIdGetRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: EventsModelsGetRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([EventsModelsGetRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const EventsIdGetResponseSchema = GetResponseEventSchema;

export const EventsIdUpdateRequestSchema = z.object({
  body: EventsModelsUpdateRequestDataSchema,
  path: z.object({
    id: EventsModelsUpdateRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([EventsModelsUpdateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const EventsIdUpdateResponseSchema = EventsModelsEventSchema;

export const EventsIdSplitSplitRequestSchema = z.object({
  body: SplitRequestDataSchema,
  path: z.object({
    id: SplitRequestIdSchema,
  }),
  query: z
    .object({
      include: z.union([SplitRequestIncludeSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Document created, URL follows
 */
export const EventsIdSplitSplitResponseSchema = SplitResponseResultSchema;

export const InstancesListRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      start: z.union([ListRequestStartSchema, z.string()]).nullish(),
      end: z.union([ListRequestEndSchema, z.string()]).nullish(),
      where: z
        .union([InstancesModelsListRequestWhereSchema, z.string()])
        .nullish(),
      include: z
        .union([InstancesModelsListRequestIncludeSchema, z.string()])
        .nullish(),
      order: z
        .union([InstancesModelsListRequestOrderSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const InstancesListResponseSchema =
  InstancesModelsListResponseResultsSchema;

export const InstancesCreateRequestSchema = z.object({
  body: InstancesModelsCreateRequestDataSchema,
  path: z.never().optional(),
  query: z
    .object({
      include: z
        .union([InstancesModelsCreateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Document created, URL follows
 */
export const InstancesCreateResponseSchema = CreateResponseInstanceSchema;

export const InstancesEventidStartGetRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    eventId: GetRequestEventIdSchema,
    start: GetRequestStartSchema,
  }),
  query: z
    .object({
      include: z
        .union([InstancesModelsGetRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const InstancesEventidStartGetResponseSchema = GetResponseInstanceSchema;

export const InstancesEventidStartUpdateRequestSchema = z.object({
  body: InstancesModelsUpdateRequestDataSchema,
  path: z.object({
    eventId: UpdateRequestEventIdSchema,
    start: UpdateRequestStartSchema,
  }),
  query: z
    .object({
      include: z
        .union([InstancesModelsUpdateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const InstancesEventidStartUpdateResponseSchema =
  UpdateResponseInstanceSchema;

export const ShowsListRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      limit: z.union([ShowsModelsListRequestLimitSchema, z.string()]).nullish(),
      offset: z
        .union([ShowsModelsListRequestOffsetSchema, z.string()])
        .nullish(),
      where: z.union([ShowsModelsListRequestWhereSchema, z.string()]).nullish(),
      include: z
        .union([ShowsModelsListRequestIncludeSchema, z.string()])
        .nullish(),
      order: z.union([ShowsModelsListRequestOrderSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const ShowsListResponseSchema = ShowsModelsListResponseResultsSchema;

export const ShowsCreateRequestSchema = z.object({
  body: ShowsModelsCreateRequestDataSchema,
  path: z.never().optional(),
  query: z
    .object({
      include: z
        .union([ShowsModelsCreateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Document created, URL follows
 */
export const ShowsCreateResponseSchema = ShowsModelsShowSchema;

export const ShowsIdGetRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: ShowsModelsGetRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([ShowsModelsGetRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const ShowsIdGetResponseSchema = GetResponseShowSchema;

export const ShowsIdUpdateRequestSchema = z.object({
  body: ShowsModelsUpdateRequestDataSchema,
  path: z.object({
    id: ShowsModelsUpdateRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([ShowsModelsUpdateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const ShowsIdUpdateResponseSchema = ShowsModelsShowSchema;
