// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * EventType
 *
 * Event types.
 */
export type SseModelsEventType = "test";

/**
 * _Event_type_OrderByInput
 */
export type ShowsModelsEventTypeOrderByInput = {
  /**
   * Type
   */
  type: "asc" | "desc";
};

/**
 * _Event_showId_OrderByInput
 */
export type ShowsModelsEventShowIdOrderByInput = {
  /**
   * Showid
   */
  showId: "asc" | "desc";
};

/**
 * _Event_id_OrderByInput
 */
export type ShowsModelsEventIdOrderByInput = {
  /**
   * Id
   */
  id: "asc" | "desc";
};

/**
 * _Event_RelevanceOrderByInput
 */
export type ShowsModelsEventRelevanceOrderByInput = {
  _relevance: ShowsModelsEventRelevanceInner;
};

/**
 * _Event_RelevanceInner
 */
export type ShowsModelsEventRelevanceInner = {
  /**
   * Fields
   */
  fields: Array<"id" | "type" | "showId">;
  /**
   * Search
   */
  search: string;
  /**
   * Sort
   */
  sort: "asc" | "desc";
};

/**
 * _EventWhereUnique_id_Input
 */
export type ShowsModelsEventWhereUniqueIdInput = {
  /**
   * Id
   */
  id: string;
};

export type ShowsModelsYearday = number | number;

/**
 * WeekdayRule
 *
 * Day rule data.
 */
export type ShowsModelsWeekdayRule = {
  day: ShowsModelsWeekday;
  /**
   * Occurrence of the day in the year.
   */
  occurrence?: ShowsModelsWeek | null;
};

export type ShowsModelsWeek = number | number;

/**
 * Weekday
 *
 * Weekday options.
 */
export type ShowsModelsWeekday =
  | "monday"
  | "tuesday"
  | "wednesday"
  | "thursday"
  | "friday"
  | "saturday"
  | "sunday";

export type ShowsModelsUpdateRequestInclude = ShowInclude | null;

/**
 * ShowIncludeFromShow
 *
 * Relational arguments for Show
 */
export type ShowsModelsShowIncludeFromShow = {
  /**
   * Events
   */
  events?: boolean | ShowsModelsFindManyEventArgsFromShow;
};

/**
 * FindManyEventArgsFromShow
 *
 * Arguments for Show
 */
export type ShowsModelsFindManyEventArgsFromShow = {
  /**
   * Take
   */
  take?: number;
  /**
   * Skip
   */
  skip?: number;
  /**
   * Orderby
   */
  orderBy?:
    | ShowsModelsEventIdOrderByInput
    | ShowsModelsEventTypeOrderByInput
    | ShowsModelsEventShowIdOrderByInput
    | ShowsModelsEventRelevanceOrderByInput
    | Array<
        | ShowsModelsEventIdOrderByInput
        | ShowsModelsEventTypeOrderByInput
        | ShowsModelsEventShowIdOrderByInput
        | ShowsModelsEventRelevanceOrderByInput
      >;
  where?: ShowsModelsEventWhereInput;
  cursor?: ShowsModelsEventWhereUniqueIdInput;
  /**
   * Distinct
   */
  distinct?: Array<"id" | "type" | "showId">;
  include?: ShowsModelsEventIncludeFromEvent;
};

/**
 * ShowArgsFromEvent
 *
 * Arguments for Event
 */
export type ShowsModelsShowArgsFromEvent = {
  include?: ShowsModelsShowIncludeFromShow;
};

/**
 * EventIncludeFromEvent
 *
 * Relational arguments for Event
 */
export type ShowsModelsEventIncludeFromEvent = {
  /**
   * Show
   */
  show?: boolean | ShowsModelsShowArgsFromEvent;
};

/**
 * ShowWhereInput
 *
 * Show arguments for searching
 */
export type ShowsModelsShowWhereInput = {
  /**
   * Id
   */
  id?: string | ShowsModelsStringFilter;
  /**
   * Title
   */
  title?: string | ShowsModelsStringFilter;
  /**
   * Description
   */
  description?: string | ShowsModelsStringFilter | null;
  events?: ShowsModelsEventListRelationFilter;
  /**
   * And
   */
  and?: Array<ShowsModelsShowWhereInput>;
  /**
   * Or
   */
  or?: Array<ShowsModelsShowWhereInput>;
  /**
   * Not
   */
  not?: Array<ShowsModelsShowWhereInput>;
};

/**
 * ShowRelationFilter
 */
export type ShowsModelsShowRelationFilter = {
  is?: ShowsModelsShowWhereInput;
  isNot?: ShowsModelsShowWhereInput;
};

/**
 * EventType
 */
export type ShowsModelsEventType = "live" | "replay" | "prerecorded";

/**
 * EventWhereInput
 *
 * Event arguments for searching
 */
export type ShowsModelsEventWhereInput = {
  /**
   * Id
   */
  id?: string | ShowsModelsStringFilter;
  type?: ShowsModelsEventType;
  /**
   * Showid
   */
  showId?: string | ShowsModelsStringFilter | null;
  show?: ShowsModelsShowRelationFilter;
  /**
   * And
   */
  and?: Array<ShowsModelsEventWhereInput>;
  /**
   * Or
   */
  or?: Array<ShowsModelsEventWhereInput>;
  /**
   * Not
   */
  not?: Array<ShowsModelsEventWhereInput>;
};

/**
 * StringFilter
 */
export type ShowsModelsStringFilter = {
  /**
   * Equals
   */
  equals?: string;
  /**
   * Notin
   */
  notIn?: Array<string>;
  /**
   * Lt
   */
  lt?: string;
  /**
   * Lte
   */
  lte?: string;
  /**
   * Gt
   */
  gt?: string;
  /**
   * Gte
   */
  gte?: string;
  /**
   * Contains
   */
  contains?: string;
  /**
   * Startswith
   */
  startswith?: string;
  /**
   * Endswith
   */
  endswith?: string;
  /**
   * In
   */
  in?: Array<string>;
  /**
   * Not
   */
  not?: string | ShowsModelsStringFilter;
  /**
   * Mode
   */
  mode?: "default" | "insensitive";
  /**
   * Search
   */
  search?: string;
};

/**
 * EventListRelationFilter
 */
export type ShowsModelsEventListRelationFilter = {
  some?: ShowsModelsEventWhereInput;
  none?: ShowsModelsEventWhereInput;
  every?: ShowsModelsEventWhereInput;
};

/**
 * ShowInclude
 *
 * Show relational arguments
 */
export type ShowInclude = {
  /**
   * Events
   */
  events?: boolean | ShowsModelsFindManyEventArgsFromShow;
};

export type ShowsModelsUpdateRequestId = string;

/**
 * ShowUpdateManyMutationInput
 *
 * Arguments for updating many records
 */
export type ShowsModelsUpdateRequestData = {
  /**
   * Id
   */
  id?: string;
  /**
   * Title
   */
  title?: string;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * UntilTermination
 *
 * Until termination data.
 */
export type ShowsModelsUntilTermination = {
  /**
   * Type
   *
   * Type of the termination.
   */
  type?: "until";
  until: ShowsModelsNaiveDatetime;
};

/**
 * Datetime without timezone.
 */
export type ShowsModelsNaiveDatetime = string;

/**
 * Timezone name.
 */
export type ShowsModelsTimezone = string;

/**
 * Duration of time.
 */
export type ShowsModelsTimedelta = string;

export type ShowsModelsTermination =
  | ({
      type: "shows_models_CountTermination";
    } & ShowsModelsCountTermination)
  | ({
      type: "shows_models_UntilTermination";
    } & ShowsModelsUntilTermination);

/**
 * CountTermination
 *
 * Count termination data.
 */
export type ShowsModelsCountTermination = {
  /**
   * Type
   *
   * Type of the termination.
   */
  type?: "count";
  /**
   * Count
   *
   * Number of instances of recurring event.
   */
  count: number;
};

/**
 * Show
 *
 * Show data.
 */
export type ShowsModelsShow = {
  /**
   * Id
   *
   * Identifier of the show.
   */
  id: string;
  /**
   * Title
   *
   * Title of the show.
   */
  title: string;
  /**
   * Description
   *
   * Description of the show.
   */
  description: string | null;
  /**
   * Events
   *
   * Events the show belongs to.
   */
  events: Array<ShowsModelsEvent> | null;
};

/**
 * Exclusion
 *
 * Exclusion data.
 */
export type ShowsModelsExclusion = {
  start: ShowsModelsNaiveDatetime;
};

/**
 * Inclusion
 *
 * Inclusion data.
 */
export type ShowsModelsInclusion = {
  start: ShowsModelsNaiveDatetime;
};

export type ShowsModelsMonth = number;

export type ShowsModelsMonthday = number | number;

export type ShowsModelsHour = number;

export type ShowsModelsMinute = number;

export type ShowsModelsSecond = number;

/**
 * Frequency
 *
 * Frequency options.
 */
export type ShowsModelsFrequency =
  | "secondly"
  | "minutely"
  | "hourly"
  | "daily"
  | "weekly"
  | "monthly"
  | "yearly";

/**
 * Recurrence
 *
 * Recurrence rule data.
 */
export type ShowsModelsRecurrence = {
  frequency: ShowsModelsFrequency;
  /**
   * Termination of the recurrence.
   */
  termination?: ShowsModelsTermination | null;
  /**
   * Interval
   *
   * Interval of the recurrence.
   */
  interval?: number | null;
  /**
   * Byseconds
   *
   * Seconds of the recurrence.
   */
  bySeconds?: Array<ShowsModelsSecond> | null;
  /**
   * Byminutes
   *
   * Minutes of the recurrence.
   */
  byMinutes?: Array<ShowsModelsMinute> | null;
  /**
   * Byhours
   *
   * Hours of the recurrence.
   */
  byHours?: Array<ShowsModelsHour> | null;
  /**
   * Byweekdays
   *
   * Weekdays of the recurrence.
   */
  byWeekdays?: Array<ShowsModelsWeekdayRule> | null;
  /**
   * Bymonthdays
   *
   * Monthdays of the recurrence.
   */
  byMonthdays?: Array<ShowsModelsMonthday> | null;
  /**
   * Byyeardays
   *
   * Yeardays of the recurrence.
   */
  byYeardays?: Array<ShowsModelsYearday> | null;
  /**
   * Byweeks
   *
   * Weeks of the recurrence.
   */
  byWeeks?: Array<ShowsModelsWeek> | null;
  /**
   * Bymonths
   *
   * Months of the recurrence.
   */
  byMonths?: Array<ShowsModelsMonth> | null;
  /**
   * Bysetpositions
   *
   * Set positions of the recurrence.
   */
  bySetPositions?: Array<ShowsModelsYearday> | null;
  /**
   * Start day of the week.
   */
  weekStart?: ShowsModelsWeekday | null;
};

/**
 * Event
 *
 * Event data.
 */
export type ShowsModelsEvent = {
  /**
   * Id
   *
   * Identifier of the event.
   */
  id: string;
  type: ShowsModelsEventType;
  /**
   * Showid
   *
   * Identifier of the show the event belongs to.
   */
  showId: string | null;
  /**
   * Show the event belongs to.
   */
  show: ShowsModelsShow | null;
  start: ShowsModelsNaiveDatetime;
  duration: ShowsModelsTimedelta;
  timezone: ShowsModelsTimezone;
  /**
   * Recurrence rule of the event.
   */
  recurrence?: ShowsModelsRecurrence | null;
  /**
   * Include
   *
   * Included instances of the event.
   */
  include?: Array<ShowsModelsInclusion> | null;
  /**
   * Exclude
   *
   * Excluded instances of the event.
   */
  exclude?: Array<ShowsModelsExclusion> | null;
};

/**
 * ShowList
 *
 * List of shows.
 */
export type ShowsModelsListResponseResults = {
  /**
   * Count
   *
   * Total number of shows that matched the query.
   */
  count: number;
  /**
   * Limit
   *
   * Maximum number of returned shows.
   */
  limit: number | null;
  /**
   * Offset
   *
   * Number of shows skipped.
   */
  offset: number | null;
  /**
   * Shows
   *
   * Shows that matched the request.
   */
  shows: Array<ShowsModelsShow>;
};

export type ShowsModelsListRequestWhere = ShowsModelsShowWhereInput | null;

export type ShowsModelsListRequestOrder =
  | ShowOrderByInput
  | Array<ShowOrderByInput>
  | null;

/**
 * _Show_description_OrderByInput
 */
export type ShowDescriptionOrderByInput = {
  /**
   * Description
   */
  description: "asc" | "desc";
};

/**
 * _Show_title_OrderByInput
 */
export type ShowTitleOrderByInput = {
  /**
   * Title
   */
  title: "asc" | "desc";
};

/**
 * _Show_id_OrderByInput
 */
export type ShowIdOrderByInput = {
  /**
   * Id
   */
  id: "asc" | "desc";
};

export type ShowOrderByInput =
  | ShowIdOrderByInput
  | ShowTitleOrderByInput
  | ShowDescriptionOrderByInput;

export type ShowsModelsListRequestOffset = number | null;

export type ShowsModelsListRequestLimit = number | null;

export type ShowsModelsListRequestInclude = ShowInclude | null;

export type ShowsModelsGetRequestInclude = ShowInclude | null;

export type ShowsModelsGetRequestId = string;

export type ShowsModelsDeleteRequestId = string;

export type ShowsModelsCreateRequestInclude = ShowInclude | null;

/**
 * ShowCreateWithoutRelationsInput
 *
 * Required arguments to the Show create method, without relations
 */
export type ShowsModelsCreateRequestData = {
  /**
   * Id
   */
  id?: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Title
   */
  title: string;
};

/**
 * _Event_type_OrderByInput
 */
export type InstancesModelsEventTypeOrderByInput = {
  /**
   * Type
   */
  type: "asc" | "desc";
};

/**
 * _Event_showId_OrderByInput
 */
export type InstancesModelsEventShowIdOrderByInput = {
  /**
   * Showid
   */
  showId: "asc" | "desc";
};

/**
 * _Event_id_OrderByInput
 */
export type InstancesModelsEventIdOrderByInput = {
  /**
   * Id
   */
  id: "asc" | "desc";
};

/**
 * _Event_RelevanceOrderByInput
 */
export type InstancesModelsEventRelevanceOrderByInput = {
  _relevance: InstancesModelsEventRelevanceInner;
};

/**
 * _Event_RelevanceInner
 */
export type InstancesModelsEventRelevanceInner = {
  /**
   * Fields
   */
  fields: Array<"id" | "type" | "showId">;
  /**
   * Search
   */
  search: string;
  /**
   * Sort
   */
  sort: "asc" | "desc";
};

/**
 * _EventWhereUnique_id_Input
 */
export type InstancesModelsEventWhereUniqueIdInput = {
  /**
   * Id
   */
  id: string;
};

export type InstancesModelsYearday = number | number;

/**
 * WeekdayRule
 *
 * Day rule data.
 */
export type InstancesModelsWeekdayRule = {
  day: InstancesModelsWeekday;
  /**
   * Occurrence of the day in the year.
   */
  occurrence?: InstancesModelsWeek | null;
};

export type InstancesModelsWeek = number | number;

/**
 * Weekday
 *
 * Weekday options.
 */
export type InstancesModelsWeekday =
  | "monday"
  | "tuesday"
  | "wednesday"
  | "thursday"
  | "friday"
  | "saturday"
  | "sunday";

export type InstancesModelsUpdateRequestInclude = InstanceInclude | null;

/**
 * EventIncludeFromEvent
 *
 * Relational arguments for Event
 */
export type InstancesModelsEventIncludeFromEvent = {
  /**
   * Show
   */
  show?: boolean | InstancesModelsShowArgsFromEvent;
};

/**
 * ShowArgsFromEvent
 *
 * Arguments for Event
 */
export type InstancesModelsShowArgsFromEvent = {
  include?: InstancesModelsShowIncludeFromShow;
};

/**
 * EventListRelationFilter
 */
export type InstancesModelsEventListRelationFilter = {
  some?: InstancesModelsEventWhereInput;
  none?: InstancesModelsEventWhereInput;
  every?: InstancesModelsEventWhereInput;
};

/**
 * EventWhereInput
 *
 * Event arguments for searching
 */
export type InstancesModelsEventWhereInput = {
  /**
   * Id
   */
  id?: string | InstancesModelsStringFilter;
  type?: InstancesModelsEventType;
  /**
   * Showid
   */
  showId?: string | InstancesModelsStringFilter | null;
  show?: InstancesModelsShowRelationFilter;
  /**
   * And
   */
  and?: Array<InstancesModelsEventWhereInput>;
  /**
   * Or
   */
  or?: Array<InstancesModelsEventWhereInput>;
  /**
   * Not
   */
  not?: Array<InstancesModelsEventWhereInput>;
};

/**
 * ShowWhereInput
 *
 * Show arguments for searching
 */
export type InstancesModelsShowWhereInput = {
  /**
   * Id
   */
  id?: string | InstancesModelsStringFilter;
  /**
   * Title
   */
  title?: string | InstancesModelsStringFilter;
  /**
   * Description
   */
  description?: string | InstancesModelsStringFilter | null;
  events?: InstancesModelsEventListRelationFilter;
  /**
   * And
   */
  and?: Array<InstancesModelsShowWhereInput>;
  /**
   * Or
   */
  or?: Array<InstancesModelsShowWhereInput>;
  /**
   * Not
   */
  not?: Array<InstancesModelsShowWhereInput>;
};

/**
 * StringFilter
 */
export type InstancesModelsStringFilter = {
  /**
   * Equals
   */
  equals?: string;
  /**
   * Notin
   */
  notIn?: Array<string>;
  /**
   * Lt
   */
  lt?: string;
  /**
   * Lte
   */
  lte?: string;
  /**
   * Gt
   */
  gt?: string;
  /**
   * Gte
   */
  gte?: string;
  /**
   * Contains
   */
  contains?: string;
  /**
   * Startswith
   */
  startswith?: string;
  /**
   * Endswith
   */
  endswith?: string;
  /**
   * In
   */
  in?: Array<string>;
  /**
   * Not
   */
  not?: string | InstancesModelsStringFilter;
  /**
   * Mode
   */
  mode?: "default" | "insensitive";
  /**
   * Search
   */
  search?: string;
};

/**
 * ShowRelationFilter
 */
export type InstancesModelsShowRelationFilter = {
  is?: InstancesModelsShowWhereInput;
  isNot?: InstancesModelsShowWhereInput;
};

/**
 * EventType
 */
export type InstancesModelsEventType = "live" | "replay" | "prerecorded";

/**
 * FindManyEventArgsFromShow
 *
 * Arguments for Show
 */
export type InstancesModelsFindManyEventArgsFromShow = {
  /**
   * Take
   */
  take?: number;
  /**
   * Skip
   */
  skip?: number;
  /**
   * Orderby
   */
  orderBy?:
    | InstancesModelsEventIdOrderByInput
    | InstancesModelsEventTypeOrderByInput
    | InstancesModelsEventShowIdOrderByInput
    | InstancesModelsEventRelevanceOrderByInput
    | Array<
        | InstancesModelsEventIdOrderByInput
        | InstancesModelsEventTypeOrderByInput
        | InstancesModelsEventShowIdOrderByInput
        | InstancesModelsEventRelevanceOrderByInput
      >;
  where?: InstancesModelsEventWhereInput;
  cursor?: InstancesModelsEventWhereUniqueIdInput;
  /**
   * Distinct
   */
  distinct?: Array<"id" | "type" | "showId">;
  include?: InstancesModelsEventIncludeFromEvent;
};

/**
 * ShowIncludeFromShow
 *
 * Relational arguments for Show
 */
export type InstancesModelsShowIncludeFromShow = {
  /**
   * Events
   */
  events?: boolean | InstancesModelsFindManyEventArgsFromShow;
};

/**
 * EventInclude
 *
 * Event relational arguments
 */
export type InstancesModelsEventInclude = {
  /**
   * Show
   */
  show?: boolean | InstancesModelsShowArgsFromEvent;
};

/**
 * EventArgsFromInstance
 *
 * Event arguments to include when querying instances.
 */
export type EventArgsFromInstance = {
  include?: InstancesModelsEventInclude;
};

/**
 * InstanceInclude
 *
 * Relations to include when querying instances.
 */
export type InstanceInclude = {
  /**
   * Event
   *
   * Event relation to include.
   */
  event?: boolean | EventArgsFromInstance;
};

/**
 * InstanceUpdateInput
 *
 * Data to update an instance.
 */
export type InstancesModelsUpdateRequestData = {
  start?: InstancesModelsNaiveDatetime;
};

/**
 * Datetime without timezone.
 */
export type InstancesModelsNaiveDatetime = string;

/**
 * UntilTermination
 *
 * Until termination data.
 */
export type InstancesModelsUntilTermination = {
  /**
   * Type
   *
   * Type of the termination.
   */
  type?: "until";
  until: InstancesModelsNaiveDatetime;
};

/**
 * Datetime in UTC.
 */
export type InstancesModelsUtcDatetime = string;

/**
 * Timezone name.
 */
export type InstancesModelsTimezone = string;

/**
 * Duration of time.
 */
export type InstancesModelsTimedelta = string;

export type InstancesModelsTermination =
  | ({
      type: "instances_models_CountTermination";
    } & InstancesModelsCountTermination)
  | ({
      type: "instances_models_UntilTermination";
    } & InstancesModelsUntilTermination);

/**
 * CountTermination
 *
 * Count termination data.
 */
export type InstancesModelsCountTermination = {
  /**
   * Type
   *
   * Type of the termination.
   */
  type?: "count";
  /**
   * Count
   *
   * Number of instances of recurring event.
   */
  count: number;
};

/**
 * Show
 *
 * Show data.
 */
export type InstancesModelsShow = {
  /**
   * Id
   *
   * Identifier of the show.
   */
  id: string;
  /**
   * Title
   *
   * Title of the show.
   */
  title: string;
  /**
   * Description
   *
   * Description of the show.
   */
  description: string | null;
  /**
   * Events
   *
   * Events the show belongs to.
   */
  events: Array<InstancesModelsEvent> | null;
};

/**
 * Event
 *
 * Event data.
 */
export type InstancesModelsEvent = {
  /**
   * Id
   *
   * Identifier of the event.
   */
  id: string;
  type: InstancesModelsEventType;
  /**
   * Showid
   *
   * Identifier of the show the event belongs to.
   */
  showId: string | null;
  /**
   * Show the event belongs to.
   */
  show: InstancesModelsShow | null;
  start: InstancesModelsNaiveDatetime;
  duration: InstancesModelsTimedelta;
  timezone: InstancesModelsTimezone;
  /**
   * Recurrence rule of the event.
   */
  recurrence?: InstancesModelsRecurrence | null;
  /**
   * Include
   *
   * Included instances of the event.
   */
  include?: Array<InstancesModelsInclusion> | null;
  /**
   * Exclude
   *
   * Excluded instances of the event.
   */
  exclude?: Array<InstancesModelsExclusion> | null;
};

/**
 * Exclusion
 *
 * Exclusion data.
 */
export type InstancesModelsExclusion = {
  start: InstancesModelsNaiveDatetime;
};

/**
 * Inclusion
 *
 * Inclusion data.
 */
export type InstancesModelsInclusion = {
  start: InstancesModelsNaiveDatetime;
};

export type InstancesModelsMonth = number;

export type InstancesModelsMonthday = number | number;

export type InstancesModelsHour = number;

export type InstancesModelsMinute = number;

export type InstancesModelsSecond = number;

/**
 * Frequency
 *
 * Frequency options.
 */
export type InstancesModelsFrequency =
  | "secondly"
  | "minutely"
  | "hourly"
  | "daily"
  | "weekly"
  | "monthly"
  | "yearly";

/**
 * Recurrence
 *
 * Recurrence rule data.
 */
export type InstancesModelsRecurrence = {
  frequency: InstancesModelsFrequency;
  /**
   * Termination of the recurrence.
   */
  termination?: InstancesModelsTermination | null;
  /**
   * Interval
   *
   * Interval of the recurrence.
   */
  interval?: number | null;
  /**
   * Byseconds
   *
   * Seconds of the recurrence.
   */
  bySeconds?: Array<InstancesModelsSecond> | null;
  /**
   * Byminutes
   *
   * Minutes of the recurrence.
   */
  byMinutes?: Array<InstancesModelsMinute> | null;
  /**
   * Byhours
   *
   * Hours of the recurrence.
   */
  byHours?: Array<InstancesModelsHour> | null;
  /**
   * Byweekdays
   *
   * Weekdays of the recurrence.
   */
  byWeekdays?: Array<InstancesModelsWeekdayRule> | null;
  /**
   * Bymonthdays
   *
   * Monthdays of the recurrence.
   */
  byMonthdays?: Array<InstancesModelsMonthday> | null;
  /**
   * Byyeardays
   *
   * Yeardays of the recurrence.
   */
  byYeardays?: Array<InstancesModelsYearday> | null;
  /**
   * Byweeks
   *
   * Weeks of the recurrence.
   */
  byWeeks?: Array<InstancesModelsWeek> | null;
  /**
   * Bymonths
   *
   * Months of the recurrence.
   */
  byMonths?: Array<InstancesModelsMonth> | null;
  /**
   * Bysetpositions
   *
   * Set positions of the recurrence.
   */
  bySetPositions?: Array<InstancesModelsYearday> | null;
  /**
   * Start day of the week.
   */
  weekStart?: InstancesModelsWeekday | null;
};

/**
 * InstanceList
 *
 * List of instances.
 */
export type InstancesModelsListResponseResults = {
  start: InstancesModelsUtcDatetime;
  end: InstancesModelsUtcDatetime;
  /**
   * Instances
   *
   * Instances that matched the request.
   */
  instances: Array<Instance>;
};

/**
 * Instance
 *
 * Instance data.
 */
export type Instance = {
  start: InstancesModelsNaiveDatetime;
  duration: InstancesModelsTimedelta;
  /**
   * Eventid
   *
   * Identifier of the event the instance belongs to.
   */
  eventId: string;
  /**
   * Event the instance belongs to.
   */
  event: InstancesModelsEvent | null;
};

export type InstancesModelsListRequestWhere = InstanceWhereInput | null;

/**
 * EventRelationFilter
 */
export type EventRelationFilter = {
  is?: InstancesModelsEventWhereInput;
  isNot?: InstancesModelsEventWhereInput;
};

/**
 * InstanceWhereInput
 *
 * Instance arguments for searching.
 */
export type InstanceWhereInput = {
  event?: EventRelationFilter;
};

export type InstancesModelsListRequestOrder =
  | InstanceOrderByInput
  | Array<InstanceOrderByInput>
  | null;

/**
 * InstanceOrderByEventIdInput
 *
 * Order by event ID of the instance.
 */
export type InstanceOrderByEventIdInput = {
  eventId: SortOrder;
};

export type SortOrder = "asc" | "desc";

/**
 * InstanceOrderByDurationInput
 *
 * Order by duration of the instance.
 */
export type InstanceOrderByDurationInput = {
  duration: SortOrder;
};

/**
 * InstanceOrderByStartInput
 *
 * Order by start datetime of the instance.
 */
export type InstanceOrderByStartInput = {
  start: SortOrder;
};

export type InstanceOrderByInput =
  | InstanceOrderByStartInput
  | InstanceOrderByDurationInput
  | InstanceOrderByEventIdInput;

export type InstancesModelsListRequestInclude = InstanceInclude | null;

export type InstancesModelsGetRequestInclude = InstanceInclude | null;

export type InstancesModelsCreateRequestInclude = InstanceInclude | null;

/**
 * InstanceCreateInput
 *
 * Data to create an instance.
 */
export type InstancesModelsCreateRequestData = {
  start: InstancesModelsNaiveDatetime;
  /**
   * Eventid
   *
   * Identifier of the event the instance belongs to.
   */
  eventId: string;
};

/**
 * _Event_type_OrderByInput
 */
export type EventsModelsEventTypeOrderByInput = {
  /**
   * Type
   */
  type: "asc" | "desc";
};

/**
 * _Event_showId_OrderByInput
 */
export type EventsModelsEventShowIdOrderByInput = {
  /**
   * Showid
   */
  showId: "asc" | "desc";
};

/**
 * _Event_id_OrderByInput
 */
export type EventsModelsEventIdOrderByInput = {
  /**
   * Id
   */
  id: "asc" | "desc";
};

/**
 * _Event_RelevanceOrderByInput
 */
export type EventsModelsEventRelevanceOrderByInput = {
  _relevance: EventsModelsEventRelevanceInner;
};

/**
 * _Event_RelevanceInner
 */
export type EventsModelsEventRelevanceInner = {
  /**
   * Fields
   */
  fields: Array<"id" | "type" | "showId">;
  /**
   * Search
   */
  search: string;
  /**
   * Sort
   */
  sort: "asc" | "desc";
};

/**
 * _EventWhereUnique_id_Input
 */
export type EventsModelsEventWhereUniqueIdInput = {
  /**
   * Id
   */
  id: string;
};

export type EventsModelsYearday = number | number;

/**
 * WeekdayRule
 *
 * Day rule data.
 */
export type EventsModelsWeekdayRule = {
  day: EventsModelsWeekday;
  /**
   * Occurrence of the day in the year.
   */
  occurrence?: EventsModelsWeek | null;
};

export type EventsModelsWeek = number | number;

/**
 * Weekday
 *
 * Weekday options.
 */
export type EventsModelsWeekday =
  | "monday"
  | "tuesday"
  | "wednesday"
  | "thursday"
  | "friday"
  | "saturday"
  | "sunday";

export type EventsModelsUpdateRequestInclude = EventsModelsEventInclude | null;

/**
 * EventIncludeFromEvent
 *
 * Relational arguments for Event
 */
export type EventsModelsEventIncludeFromEvent = {
  /**
   * Show
   */
  show?: boolean | EventsModelsShowArgsFromEvent;
};

/**
 * ShowArgsFromEvent
 *
 * Arguments for Event
 */
export type EventsModelsShowArgsFromEvent = {
  include?: EventsModelsShowIncludeFromShow;
};

/**
 * EventListRelationFilter
 */
export type EventsModelsEventListRelationFilter = {
  some?: EventsModelsEventWhereInput;
  none?: EventsModelsEventWhereInput;
  every?: EventsModelsEventWhereInput;
};

/**
 * EventWhereInput
 *
 * Event arguments for searching
 */
export type EventsModelsEventWhereInput = {
  /**
   * Id
   */
  id?: string | EventsModelsStringFilter;
  type?: EventsModelsEventType;
  /**
   * Showid
   */
  showId?: string | EventsModelsStringFilter | null;
  show?: EventsModelsShowRelationFilter;
  /**
   * And
   */
  and?: Array<EventsModelsEventWhereInput>;
  /**
   * Or
   */
  or?: Array<EventsModelsEventWhereInput>;
  /**
   * Not
   */
  not?: Array<EventsModelsEventWhereInput>;
};

/**
 * ShowWhereInput
 *
 * Show arguments for searching
 */
export type EventsModelsShowWhereInput = {
  /**
   * Id
   */
  id?: string | EventsModelsStringFilter;
  /**
   * Title
   */
  title?: string | EventsModelsStringFilter;
  /**
   * Description
   */
  description?: string | EventsModelsStringFilter | null;
  events?: EventsModelsEventListRelationFilter;
  /**
   * And
   */
  and?: Array<EventsModelsShowWhereInput>;
  /**
   * Or
   */
  or?: Array<EventsModelsShowWhereInput>;
  /**
   * Not
   */
  not?: Array<EventsModelsShowWhereInput>;
};

/**
 * StringFilter
 */
export type EventsModelsStringFilter = {
  /**
   * Equals
   */
  equals?: string;
  /**
   * Notin
   */
  notIn?: Array<string>;
  /**
   * Lt
   */
  lt?: string;
  /**
   * Lte
   */
  lte?: string;
  /**
   * Gt
   */
  gt?: string;
  /**
   * Gte
   */
  gte?: string;
  /**
   * Contains
   */
  contains?: string;
  /**
   * Startswith
   */
  startswith?: string;
  /**
   * Endswith
   */
  endswith?: string;
  /**
   * In
   */
  in?: Array<string>;
  /**
   * Not
   */
  not?: string | EventsModelsStringFilter;
  /**
   * Mode
   */
  mode?: "default" | "insensitive";
  /**
   * Search
   */
  search?: string;
};

/**
 * ShowRelationFilter
 */
export type EventsModelsShowRelationFilter = {
  is?: EventsModelsShowWhereInput;
  isNot?: EventsModelsShowWhereInput;
};

/**
 * EventType
 */
export type EventsModelsEventType = "live" | "replay" | "prerecorded";

/**
 * FindManyEventArgsFromShow
 *
 * Arguments for Show
 */
export type EventsModelsFindManyEventArgsFromShow = {
  /**
   * Take
   */
  take?: number;
  /**
   * Skip
   */
  skip?: number;
  /**
   * Orderby
   */
  orderBy?:
    | EventsModelsEventIdOrderByInput
    | EventsModelsEventTypeOrderByInput
    | EventsModelsEventShowIdOrderByInput
    | EventsModelsEventRelevanceOrderByInput
    | Array<
        | EventsModelsEventIdOrderByInput
        | EventsModelsEventTypeOrderByInput
        | EventsModelsEventShowIdOrderByInput
        | EventsModelsEventRelevanceOrderByInput
      >;
  where?: EventsModelsEventWhereInput;
  cursor?: EventsModelsEventWhereUniqueIdInput;
  /**
   * Distinct
   */
  distinct?: Array<"id" | "type" | "showId">;
  include?: EventsModelsEventIncludeFromEvent;
};

/**
 * ShowIncludeFromShow
 *
 * Relational arguments for Show
 */
export type EventsModelsShowIncludeFromShow = {
  /**
   * Events
   */
  events?: boolean | EventsModelsFindManyEventArgsFromShow;
};

/**
 * EventInclude
 *
 * Event relational arguments
 */
export type EventsModelsEventInclude = {
  /**
   * Show
   */
  show?: boolean | EventsModelsShowArgsFromEvent;
};

export type EventsModelsUpdateRequestId = string;

/**
 * EventUpdateInput
 *
 * Data to update an event.
 */
export type EventsModelsUpdateRequestData = {
  /**
   * Id
   */
  id?: string;
  type?: EventsModelsEventType;
  start?: EventsModelsNaiveDatetime;
  duration?: EventsModelsTimedelta;
  timezone?: EventsModelsTimezone;
  /**
   * Recurrence rule of the event.
   */
  recurrence?: RecurrenceUpdateInput | null;
  /**
   * Include
   *
   * Included instances of the event.
   */
  include?: Array<EventsModelsInclusion> | null;
  /**
   * Exclude
   *
   * Excluded instances of the event.
   */
  exclude?: Array<EventsModelsExclusion> | null;
};

/**
 * Exclusion
 *
 * Exclusion data.
 */
export type EventsModelsExclusion = {
  start: EventsModelsNaiveDatetime;
};

/**
 * Datetime without timezone.
 */
export type EventsModelsNaiveDatetime = string;

/**
 * Inclusion
 *
 * Inclusion data.
 */
export type EventsModelsInclusion = {
  start: EventsModelsNaiveDatetime;
};

export type EventsModelsMonth = number;

export type EventsModelsMonthday = number | number;

export type EventsModelsHour = number;

export type EventsModelsMinute = number;

export type EventsModelsSecond = number;

/**
 * UntilTermination
 *
 * Until termination data.
 */
export type EventsModelsUntilTermination = {
  /**
   * Type
   *
   * Type of the termination.
   */
  type?: "until";
  until: EventsModelsNaiveDatetime;
};

/**
 * CountTermination
 *
 * Count termination data.
 */
export type EventsModelsCountTermination = {
  /**
   * Type
   *
   * Type of the termination.
   */
  type?: "count";
  /**
   * Count
   *
   * Number of instances of recurring event.
   */
  count: number;
};

export type EventsModelsTermination =
  | ({
      type: "events_models_CountTermination";
    } & EventsModelsCountTermination)
  | ({
      type: "events_models_UntilTermination";
    } & EventsModelsUntilTermination);

/**
 * Frequency
 *
 * Frequency options.
 */
export type EventsModelsFrequency =
  | "secondly"
  | "minutely"
  | "hourly"
  | "daily"
  | "weekly"
  | "monthly"
  | "yearly";

/**
 * RecurrenceUpdateInput
 *
 * Data to update a recurrence rule.
 */
export type RecurrenceUpdateInput = {
  frequency?: EventsModelsFrequency;
  /**
   * Termination of the recurrence.
   */
  termination?: EventsModelsTermination | null;
  /**
   * Interval
   *
   * Interval of the recurrence.
   */
  interval?: number | null;
  /**
   * Byseconds
   *
   * Seconds of the recurrence.
   */
  bySeconds?: Array<EventsModelsSecond> | null;
  /**
   * Byminutes
   *
   * Minutes of the recurrence.
   */
  byMinutes?: Array<EventsModelsMinute> | null;
  /**
   * Byhours
   *
   * Hours of the recurrence.
   */
  byHours?: Array<EventsModelsHour> | null;
  /**
   * Byweekdays
   *
   * Weekdays of the recurrence.
   */
  byWeekdays?: Array<EventsModelsWeekdayRule> | null;
  /**
   * Bymonthdays
   *
   * Monthdays of the recurrence.
   */
  byMonthdays?: Array<EventsModelsMonthday> | null;
  /**
   * Byyeardays
   *
   * Yeardays of the recurrence.
   */
  byYeardays?: Array<EventsModelsYearday> | null;
  /**
   * Byweeks
   *
   * Weeks of the recurrence.
   */
  byWeeks?: Array<EventsModelsWeek> | null;
  /**
   * Bymonths
   *
   * Months of the recurrence.
   */
  byMonths?: Array<EventsModelsMonth> | null;
  /**
   * Bysetpositions
   *
   * Set positions of the recurrence.
   */
  bySetPositions?: Array<EventsModelsYearday> | null;
  /**
   * Start day of the week.
   */
  weekStart?: EventsModelsWeekday | null;
};

/**
 * Timezone name.
 */
export type EventsModelsTimezone = string;

/**
 * Duration of time.
 */
export type EventsModelsTimedelta = string;

/**
 * Datetime in UTC.
 */
export type EventsModelsUtcDatetime = string;

/**
 * Show
 *
 * Show data.
 */
export type EventsModelsShow = {
  /**
   * Id
   *
   * Identifier of the show.
   */
  id: string;
  /**
   * Title
   *
   * Title of the show.
   */
  title: string;
  /**
   * Description
   *
   * Description of the show.
   */
  description: string | null;
  /**
   * Events
   *
   * Events the show belongs to.
   */
  events: Array<EventsModelsEvent> | null;
};

/**
 * Event
 *
 * Event data.
 */
export type EventsModelsEvent = {
  /**
   * Id
   *
   * Identifier of the event.
   */
  id: string;
  type: EventsModelsEventType;
  /**
   * Showid
   *
   * Identifier of the show the event belongs to.
   */
  showId: string | null;
  /**
   * Show the event belongs to.
   */
  show: EventsModelsShow | null;
  start: EventsModelsNaiveDatetime;
  duration: EventsModelsTimedelta;
  timezone: EventsModelsTimezone;
  /**
   * Recurrence rule of the event.
   */
  recurrence?: EventsModelsRecurrence | null;
  /**
   * Include
   *
   * Included instances of the event.
   */
  include?: Array<EventsModelsInclusion> | null;
  /**
   * Exclude
   *
   * Excluded instances of the event.
   */
  exclude?: Array<EventsModelsExclusion> | null;
};

/**
 * Recurrence
 *
 * Recurrence rule data.
 */
export type EventsModelsRecurrence = {
  frequency: EventsModelsFrequency;
  /**
   * Termination of the recurrence.
   */
  termination?: EventsModelsTermination | null;
  /**
   * Interval
   *
   * Interval of the recurrence.
   */
  interval?: number | null;
  /**
   * Byseconds
   *
   * Seconds of the recurrence.
   */
  bySeconds?: Array<EventsModelsSecond> | null;
  /**
   * Byminutes
   *
   * Minutes of the recurrence.
   */
  byMinutes?: Array<EventsModelsMinute> | null;
  /**
   * Byhours
   *
   * Hours of the recurrence.
   */
  byHours?: Array<EventsModelsHour> | null;
  /**
   * Byweekdays
   *
   * Weekdays of the recurrence.
   */
  byWeekdays?: Array<EventsModelsWeekdayRule> | null;
  /**
   * Bymonthdays
   *
   * Monthdays of the recurrence.
   */
  byMonthdays?: Array<EventsModelsMonthday> | null;
  /**
   * Byyeardays
   *
   * Yeardays of the recurrence.
   */
  byYeardays?: Array<EventsModelsYearday> | null;
  /**
   * Byweeks
   *
   * Weeks of the recurrence.
   */
  byWeeks?: Array<EventsModelsWeek> | null;
  /**
   * Bymonths
   *
   * Months of the recurrence.
   */
  byMonths?: Array<EventsModelsMonth> | null;
  /**
   * Bysetpositions
   *
   * Set positions of the recurrence.
   */
  bySetPositions?: Array<EventsModelsYearday> | null;
  /**
   * Start day of the week.
   */
  weekStart?: EventsModelsWeekday | null;
};

/**
 * EventList
 *
 * List of events.
 */
export type EventsModelsListResponseResults = {
  /**
   * Count
   *
   * Total number of events that matched the query.
   */
  count: number;
  /**
   * Limit
   *
   * Maximum number of returned events.
   */
  limit: number | null;
  /**
   * Offset
   *
   * Number of events skipped.
   */
  offset: number | null;
  /**
   * Events
   *
   * Events that matched the request.
   */
  events: Array<EventsModelsEvent>;
};

export type EventsModelsListRequestWhere = EventsModelsEventWhereInput | null;

export type EventsModelsListRequestOrder =
  | EventOrderByInput
  | Array<EventOrderByInput>
  | null;

/**
 * EventOrderByTimezoneInput
 *
 * Order by timezone.
 */
export type EventOrderByTimezoneInput = {
  /**
   * Timezone
   */
  timezone: "asc" | "desc";
};

/**
 * EventOrderByEndInput
 *
 * Order by end time.
 */
export type EventOrderByEndInput = {
  /**
   * End
   */
  end: "asc" | "desc";
};

/**
 * EventOrderByStartInput
 *
 * Order by start time.
 */
export type EventOrderByStartInput = {
  /**
   * Start
   */
  start: "asc" | "desc";
};

export type EventOrderByInput =
  | EventsModelsEventIdOrderByInput
  | EventsModelsEventTypeOrderByInput
  | EventsModelsEventShowIdOrderByInput
  | EventOrderByStartInput
  | EventOrderByEndInput
  | EventOrderByTimezoneInput;

export type EventsModelsListRequestOffset = number | null;

export type EventsModelsListRequestLimit = number | null;

export type EventsModelsListRequestInclude = EventsModelsEventInclude | null;

export type EventsModelsGetRequestInclude = EventsModelsEventInclude | null;

export type EventsModelsGetRequestId = string;

export type EventsModelsDeleteRequestId = string;

export type EventsModelsCreateRequestInclude = EventsModelsEventInclude | null;

/**
 * EventCreateInput
 *
 * Data to create an event.
 */
export type EventsModelsCreateRequestData = {
  /**
   * Id
   */
  id?: string;
  /**
   * Showid
   */
  showId?: string | null;
  type: EventsModelsEventType;
  start: EventsModelsNaiveDatetime;
  duration: EventsModelsTimedelta;
  timezone: EventsModelsTimezone;
  /**
   * Recurrence rule of the event.
   */
  recurrence?: EventsModelsRecurrence | null;
  /**
   * Include
   *
   * Included instances of the event.
   */
  include?: Array<EventsModelsInclusion> | null;
  /**
   * Exclude
   *
   * Excluded instances of the event.
   */
  exclude?: Array<EventsModelsExclusion> | null;
};

/**
 * Instance
 *
 * Instance data.
 */
export type UpdateResponseInstance = {
  start: InstancesModelsNaiveDatetime;
  duration: InstancesModelsTimedelta;
  /**
   * Eventid
   *
   * Identifier of the event the instance belongs to.
   */
  eventId: string;
  /**
   * Event the instance belongs to.
   */
  event: InstancesModelsEvent | null;
};

/**
 * Datetime without timezone.
 */
export type UpdateRequestStart = string;

export type UpdateRequestEventId = string;

/**
 * TimeRangeQuery
 *
 * Query for events in a time range.
 */
export type TimeRangeQuery = {
  /**
   * Type
   *
   * Type of the query.
   */
  type?: "time-range";
  /**
   * Beginning of the time range in UTC.
   */
  start?: EventsModelsUtcDatetime | null;
  /**
   * End of the time range in UTC.
   */
  end?: EventsModelsUtcDatetime | null;
};

/**
 * Result
 *
 * Result of the test.
 */
export type TestResponseResult = {
  /**
   * Success
   *
   * Indicates if the test was successful.
   */
  success: boolean;
  /**
   * Message
   *
   * Message returned from the test.
   */
  message: string;
};

export type TestRequestParameters = Parameters | null;

/**
 * Parameters
 *
 * Parameters for testing.
 */
export type Parameters = {
  /**
   * Message
   *
   * Optional message to include in the test.
   */
  message?: string | null;
};

export type SubscribeRequestTypes = string | Array<SseModelsEventType> | null;

/**
 * SplitResult
 *
 * Result of splitting an event.
 */
export type SplitResponseResult = {
  before: GetResponseEvent;
  after: EventsModelsEvent;
};

/**
 * Event
 *
 * Event data.
 */
export type GetResponseEvent = {
  /**
   * Id
   *
   * Identifier of the event.
   */
  id: string;
  type: EventsModelsEventType;
  /**
   * Showid
   *
   * Identifier of the show the event belongs to.
   */
  showId: string | null;
  /**
   * Show the event belongs to.
   */
  show: EventsModelsShow | null;
  start: EventsModelsNaiveDatetime;
  duration: EventsModelsTimedelta;
  timezone: EventsModelsTimezone;
  /**
   * Recurrence rule of the event.
   */
  recurrence?: EventsModelsRecurrence | null;
  /**
   * Include
   *
   * Included instances of the event.
   */
  include?: Array<EventsModelsInclusion> | null;
  /**
   * Exclude
   *
   * Excluded instances of the event.
   */
  exclude?: Array<EventsModelsExclusion> | null;
};

export type SplitRequestInclude = EventsModelsEventInclude | null;

export type SplitRequestId = string;

/**
 * EventSplitInput
 *
 * Data to split an event.
 */
export type SplitRequestData = {
  at: EventsModelsNaiveDatetime;
  /**
   * Data to update the event after the split.
   */
  update?: EventUpdateInput | null;
};

/**
 * EventUpdateInput
 *
 * Data to update an event.
 */
export type EventUpdateInput = {
  /**
   * Id
   */
  id?: string;
  type?: EventsModelsEventType;
  start?: EventsModelsNaiveDatetime;
  duration?: EventsModelsTimedelta;
  timezone?: EventsModelsTimezone;
  /**
   * Recurrence rule of the event.
   */
  recurrence?: RecurrenceUpdateInput | null;
  /**
   * Include
   *
   * Included instances of the event.
   */
  include?: Array<EventsModelsInclusion> | null;
  /**
   * Exclude
   *
   * Excluded instances of the event.
   */
  exclude?: Array<EventsModelsExclusion> | null;
};

/**
 * RecurringQuery
 *
 * Query for recurring events.
 */
export type RecurringQuery = {
  /**
   * Type
   *
   * Type of the query.
   */
  type?: "recurring";
  /**
   * Recurring
   *
   * Whether to search for recurring or non-recurring events.
   */
  recurring: boolean;
};

export type Query =
  | ({
      type: "TimeRangeQuery";
    } & TimeRangeQuery)
  | ({
      type: "RecurringQuery";
    } & RecurringQuery);

/**
 * Datetime in UTC.
 */
export type ListRequestStart = string;

export type ListRequestQuery = Query | null;

/**
 * Datetime in UTC.
 */
export type ListRequestEnd = string;

/**
 * Show
 *
 * Show data.
 */
export type GetResponseShow = {
  /**
   * Id
   *
   * Identifier of the show.
   */
  id: string;
  /**
   * Title
   *
   * Title of the show.
   */
  title: string;
  /**
   * Description
   *
   * Description of the show.
   */
  description: string | null;
  /**
   * Events
   *
   * Events the show belongs to.
   */
  events: Array<ShowsModelsEvent> | null;
};

export type GetResponseInstance = Instance | null;

/**
 * Datetime without timezone.
 */
export type GetRequestStart = string;

export type GetRequestEventId = string;

/**
 * Datetime without timezone.
 */
export type DeleteRequestStart = string;

export type DeleteRequestEventId = string;

/**
 * Instance
 *
 * Instance data.
 */
export type CreateResponseInstance = {
  start: InstancesModelsNaiveDatetime;
  duration: InstancesModelsTimedelta;
  /**
   * Eventid
   *
   * Identifier of the event the instance belongs to.
   */
  eventId: string;
  /**
   * Event the instance belongs to.
   */
  event: InstancesModelsEvent | null;
};

export type EventsListRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of events to return. Default is 10.
     */
    limit?: EventsModelsListRequestLimit | string | null;
    /**
     * Number of events to skip.
     */
    offset?: EventsModelsListRequestOffset | string | null;
    /**
     * Filter to apply to find events.
     */
    where?: EventsModelsListRequestWhere | string | null;
    /**
     * Advanced query to apply to find events.
     */
    query?: ListRequestQuery | string | null;
    /**
     * Relations to include in the response.
     */
    include?: EventsModelsListRequestInclude | string | null;
    /**
     * Order to apply to the results.
     */
    order?: EventsModelsListRequestOrder | string | null;
  };
  url: "/events";
};

export type EventsListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type EventsListError = EventsListErrors[keyof EventsListErrors];

export type EventsListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: EventsModelsListResponseResults;
};

export type EventsListResponse = EventsListResponses[keyof EventsListResponses];

export type EventsCreateRequest = {
  body: EventsModelsCreateRequestData;
  path?: never;
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: EventsModelsCreateRequestInclude | string | null;
  };
  url: "/events";
};

export type EventsCreateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Conflict Exception
   */
  409: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type EventsCreateError = EventsCreateErrors[keyof EventsCreateErrors];

export type EventsCreateResponses = {
  /**
   * Document created, URL follows
   */
  201: EventsModelsEvent;
};

export type EventsCreateResponse =
  EventsCreateResponses[keyof EventsCreateResponses];

export type EventsIdDeleteRequest = {
  body?: never;
  path: {
    id: EventsModelsDeleteRequestId;
  };
  query?: never;
  url: "/events/{id}";
};

export type EventsIdDeleteErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type EventsIdDeleteError =
  EventsIdDeleteErrors[keyof EventsIdDeleteErrors];

export type EventsIdDeleteResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type EventsIdDeleteResponse =
  EventsIdDeleteResponses[keyof EventsIdDeleteResponses];

export type EventsIdGetRequest = {
  body?: never;
  path: {
    id: EventsModelsGetRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: EventsModelsGetRequestInclude | string | null;
  };
  url: "/events/{id}";
};

export type EventsIdGetErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type EventsIdGetError = EventsIdGetErrors[keyof EventsIdGetErrors];

export type EventsIdGetResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetResponseEvent;
};

export type EventsIdGetResponse =
  EventsIdGetResponses[keyof EventsIdGetResponses];

export type EventsIdUpdateRequest = {
  body: EventsModelsUpdateRequestData;
  path: {
    id: EventsModelsUpdateRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: EventsModelsUpdateRequestInclude | string | null;
  };
  url: "/events/{id}";
};

export type EventsIdUpdateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Conflict Exception
   */
  409: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type EventsIdUpdateError =
  EventsIdUpdateErrors[keyof EventsIdUpdateErrors];

export type EventsIdUpdateResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: EventsModelsEvent;
};

export type EventsIdUpdateResponse =
  EventsIdUpdateResponses[keyof EventsIdUpdateResponses];

export type EventsIdSplitSplitRequest = {
  body: SplitRequestData;
  path: {
    id: SplitRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: SplitRequestInclude | string | null;
  };
  url: "/events/{id}/split";
};

export type EventsIdSplitSplitErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Conflict Exception
   */
  409: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type EventsIdSplitSplitError =
  EventsIdSplitSplitErrors[keyof EventsIdSplitSplitErrors];

export type EventsIdSplitSplitResponses = {
  /**
   * Document created, URL follows
   */
  201: SplitResponseResult;
};

export type EventsIdSplitSplitResponse =
  EventsIdSplitSplitResponses[keyof EventsIdSplitSplitResponses];

export type InstancesListRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start datetime in UTC to filter instances. Default is now.
     */
    start?: ListRequestStart | string | null;
    /**
     * End datetime in UTC to filter instances. Default is now.
     */
    end?: ListRequestEnd | string | null;
    /**
     * Filter to apply to find instances.
     */
    where?: InstancesModelsListRequestWhere | string | null;
    /**
     * Relations to include in the response.
     */
    include?: InstancesModelsListRequestInclude | string | null;
    /**
     * Order to apply to the results.
     */
    order?: InstancesModelsListRequestOrder | string | null;
  };
  url: "/instances";
};

export type InstancesListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type InstancesListError = InstancesListErrors[keyof InstancesListErrors];

export type InstancesListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: InstancesModelsListResponseResults;
};

export type InstancesListResponse =
  InstancesListResponses[keyof InstancesListResponses];

export type InstancesCreateRequest = {
  body: InstancesModelsCreateRequestData;
  path?: never;
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: InstancesModelsCreateRequestInclude | string | null;
  };
  url: "/instances";
};

export type InstancesCreateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Conflict Exception
   */
  409: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type InstancesCreateError =
  InstancesCreateErrors[keyof InstancesCreateErrors];

export type InstancesCreateResponses = {
  /**
   * Document created, URL follows
   */
  201: CreateResponseInstance;
};

export type InstancesCreateResponse =
  InstancesCreateResponses[keyof InstancesCreateResponses];

export type InstancesEventidStartDeleteRequest = {
  body?: never;
  path: {
    eventId: DeleteRequestEventId;
    /**
     * Datetime without timezone.
     */
    start: DeleteRequestStart;
  };
  query?: never;
  url: "/instances/{eventId}/{start}";
};

export type InstancesEventidStartDeleteErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type InstancesEventidStartDeleteError =
  InstancesEventidStartDeleteErrors[keyof InstancesEventidStartDeleteErrors];

export type InstancesEventidStartDeleteResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type InstancesEventidStartDeleteResponse =
  InstancesEventidStartDeleteResponses[keyof InstancesEventidStartDeleteResponses];

export type InstancesEventidStartGetRequest = {
  body?: never;
  path: {
    eventId: GetRequestEventId;
    /**
     * Datetime without timezone.
     */
    start: GetRequestStart;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: InstancesModelsGetRequestInclude | string | null;
  };
  url: "/instances/{eventId}/{start}";
};

export type InstancesEventidStartGetErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type InstancesEventidStartGetError =
  InstancesEventidStartGetErrors[keyof InstancesEventidStartGetErrors];

export type InstancesEventidStartGetResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetResponseInstance;
};

export type InstancesEventidStartGetResponse =
  InstancesEventidStartGetResponses[keyof InstancesEventidStartGetResponses];

export type InstancesEventidStartUpdateRequest = {
  body: InstancesModelsUpdateRequestData;
  path: {
    eventId: UpdateRequestEventId;
    /**
     * Datetime without timezone.
     */
    start: UpdateRequestStart;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: InstancesModelsUpdateRequestInclude | string | null;
  };
  url: "/instances/{eventId}/{start}";
};

export type InstancesEventidStartUpdateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Conflict Exception
   */
  409: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type InstancesEventidStartUpdateError =
  InstancesEventidStartUpdateErrors[keyof InstancesEventidStartUpdateErrors];

export type InstancesEventidStartUpdateResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: UpdateResponseInstance;
};

export type InstancesEventidStartUpdateResponse =
  InstancesEventidStartUpdateResponses[keyof InstancesEventidStartUpdateResponses];

export type PingPingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingPingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingPingResponse = PingPingResponses[keyof PingPingResponses];

export type PingHeadpingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingHeadpingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingHeadpingResponse =
  PingHeadpingResponses[keyof PingHeadpingResponses];

export type ShowsListRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of shows to return. Default is 10.
     */
    limit?: ShowsModelsListRequestLimit | string | null;
    /**
     * Number of shows to skip.
     */
    offset?: ShowsModelsListRequestOffset | string | null;
    /**
     * Filter to apply to find shows.
     */
    where?: ShowsModelsListRequestWhere | string | null;
    /**
     * Relations to include in the response.
     */
    include?: ShowsModelsListRequestInclude | string | null;
    /**
     * Order to apply to the results.
     */
    order?: ShowsModelsListRequestOrder | string | null;
  };
  url: "/shows";
};

export type ShowsListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type ShowsListError = ShowsListErrors[keyof ShowsListErrors];

export type ShowsListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: ShowsModelsListResponseResults;
};

export type ShowsListResponse = ShowsListResponses[keyof ShowsListResponses];

export type ShowsCreateRequest = {
  body: ShowsModelsCreateRequestData;
  path?: never;
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: ShowsModelsCreateRequestInclude | string | null;
  };
  url: "/shows";
};

export type ShowsCreateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Conflict Exception
   */
  409: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type ShowsCreateError = ShowsCreateErrors[keyof ShowsCreateErrors];

export type ShowsCreateResponses = {
  /**
   * Document created, URL follows
   */
  201: ShowsModelsShow;
};

export type ShowsCreateResponse =
  ShowsCreateResponses[keyof ShowsCreateResponses];

export type ShowsIdDeleteRequest = {
  body?: never;
  path: {
    id: ShowsModelsDeleteRequestId;
  };
  query?: never;
  url: "/shows/{id}";
};

export type ShowsIdDeleteErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type ShowsIdDeleteError = ShowsIdDeleteErrors[keyof ShowsIdDeleteErrors];

export type ShowsIdDeleteResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type ShowsIdDeleteResponse =
  ShowsIdDeleteResponses[keyof ShowsIdDeleteResponses];

export type ShowsIdGetRequest = {
  body?: never;
  path: {
    id: ShowsModelsGetRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: ShowsModelsGetRequestInclude | string | null;
  };
  url: "/shows/{id}";
};

export type ShowsIdGetErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type ShowsIdGetError = ShowsIdGetErrors[keyof ShowsIdGetErrors];

export type ShowsIdGetResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetResponseShow;
};

export type ShowsIdGetResponse = ShowsIdGetResponses[keyof ShowsIdGetResponses];

export type ShowsIdUpdateRequest = {
  body: ShowsModelsUpdateRequestData;
  path: {
    id: ShowsModelsUpdateRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: ShowsModelsUpdateRequestInclude | string | null;
  };
  url: "/shows/{id}";
};

export type ShowsIdUpdateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Conflict Exception
   */
  409: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type ShowsIdUpdateError = ShowsIdUpdateErrors[keyof ShowsIdUpdateErrors];

export type ShowsIdUpdateResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: ShowsModelsShow;
};

export type ShowsIdUpdateResponse =
  ShowsIdUpdateResponses[keyof ShowsIdUpdateResponses];

export type SseSubscribeRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Types of events to subscribe to.
     */
    types?: SubscribeRequestTypes | string | null;
  };
  url: "/sse";
};

export type SseSubscribeErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type SseSubscribeError = SseSubscribeErrors[keyof SseSubscribeErrors];

export type SseSubscribeResponses = {
  /**
   * Request fulfilled, stream of Server-Sent Events follows
   */
  200: string;
};

export type SseSubscribeResponse =
  SseSubscribeResponses[keyof SseSubscribeResponses];

export type TestTestRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Parameters for testing.
     */
    parameters?: TestRequestParameters | string | null;
  };
  url: "/test";
};

export type TestTestErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TestTestError = TestTestErrors[keyof TestTestErrors];

export type TestTestResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: TestResponseResult;
};

export type TestTestResponse = TestTestResponses[keyof TestTestResponses];
