/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/ping": {
    delete?: never;
    /**
     * Ping
     * @description Ping.
     */
    get: operations["PingPing"];
    /**
     * Ping headers
     * @description Ping headers.
     */
    head: operations["PingHeadping"];
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  "/stream": {
    delete?: never;
    get?: never;
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    /**
     * Request a stream
     * @description Request a stream.
     */
    post: operations["StreamStream"];
    put?: never;
    trace?: never;
  };
};
export type webhooks = { [key: string]: never };
export type components = {
  headers: never;
  parameters: never;
  pathItems: never;
  requestBodies: never;
  responses: never;
  schemas: {
    /**
     * SRTServer
     * @description SRT server configuration.
     */
    SRTServer: {
      host: string;
      password?: null | string;
      port: number;
    };
    /**
     * StreamRequestData
     * @description Data for the request.
     */
    StreamRequestData: {
      /**
       * @description Audio codec.
       * @default opus
       * @enum {string}
       */
      codec: "opus";
      /**
       * @description Audio format.
       * @default ogg
       * @enum {string}
       */
      format: "ogg";
      srt: components["schemas"]["SRTServer"];
      /** @description STUN server configuration. */
      stun?: components["schemas"]["STUNServer"] | null;
    };
    /** StreamResponseData */
    StreamResponseData: {
      /** @description Port to stream to. */
      port: number;
      stun: components["schemas"]["STUNServer"];
    };
    /** STUNServer */
    STUNServer: {
      host: string;
      port: number;
    };
  };
};
export type $defs = { [key: string]: never };
export type operations = {
  PingHeadping: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
          "cache-control"?: string;
        };
      };
    };
  };
  PingPing: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        content: {
          "application/json": null;
        };
        headers: {
          [name: string]: unknown;
          "cache-control"?: string;
        };
      };
    };
  };
  StreamStream: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StreamRequestData"];
      };
    };
    responses: {
      /** @description Document created, URL follows */
      201: {
        content: {
          "application/json": components["schemas"]["StreamResponseData"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Conflict */
      409: {
        content: {
          "application/json": {
            detail: string;
            extra?:
              | {
                  [key: string]: unknown;
                }
              | null
              | unknown[];
            status_code: number;
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
};
