/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/ping": {
    /**
     * Ping
     * @description Do nothing.
     */
    get: operations["PingPing"];
  };
  "/stream": {
    /**
     * Request a stream
     * @description Request a stream.
     */
    post: operations["StreamStream"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Request */
    Request: {
      /**
       * Request.STUN
       * @description STUN server to use.
       */
      stun?: null | components["schemas"]["STUNServer"];
      /**
       * Request.Codec
       * @description Codec of the media in the stream.
       * @enum {string}
       */
      codec?: "opus";
      /**
       * Request.Format
       * @description Format of the media in the stream.
       * @enum {string}
       */
      format?: "ogg";
      srt: components["schemas"]["SRTServer"];
    };
    /** STUNServer */
    STUNServer: {
      /**
       * STUNServer.Host
       * @description Host of the STUN server.
       */
      host: string;
      /**
       * STUNServer.Port
       * @description Port of the STUN server.
       */
      port: number;
    };
    /**
     * SRTServer
     * @description SRT server to send the stream to.
     */
    SRTServer: {
      /**
       * SRTServer.Host
       * @description Host of the SRT server.
       */
      host: string;
      /**
       * SRTServer.Port
       * @description Port of the SRT server.
       */
      port: number;
      /**
       * SRTServer.Password
       * @description Password to use for the SRT stream.
       */
      password?: null | string;
    };
    /** Response */
    Response: {
      /**
       * Response.Port
       * @description Port to use to connect to the stream.
       */
      port: number;
      stun: components["schemas"]["STUNServer"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * Ping
   * @description Do nothing.
   */
  PingPing: {
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        headers: {
          "cache-control"?: string;
        };
        content: {
          "application/json": null;
        };
      };
    };
  };
  /**
   * Request a stream
   * @description Request a stream.
   */
  StreamStream: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Request"];
      };
    };
    responses: {
      /** @description Document created, URL follows */
      201: {
        headers: {};
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
      /** @description Conflict */
      409: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
}
