/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/ping": {
    /**
     * Ping
     * @description Ping.
     */
    get: operations["PingPing"];
    /**
     * Ping headers
     * @description Ping headers.
     */
    head: operations["PingHeadping"];
  };
  "/stream": {
    /**
     * Request a stream
     * @description Request a stream.
     */
    post: operations["StreamStream"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * SRTServer
     * @description SRT server configuration.
     */
    SRTServer: {
      host: string;
      port: number;
      password?: null | string;
    };
    /** STUNServer */
    STUNServer: {
      host: string;
      port: number;
    };
    /**
     * StreamRequestData
     * @description Data for the request.
     */
    StreamRequestData: {
      /**
       * @description Audio codec.
       * @default opus
       * @enum {string}
       */
      codec?: "opus";
      /**
       * @description Audio format.
       * @default ogg
       * @enum {string}
       */
      format?: "ogg";
      srt: components["schemas"]["SRTServer"];
      /** @description STUN server configuration. */
      stun?: null | components["schemas"]["STUNServer"];
    };
    /** StreamResponseData */
    StreamResponseData: {
      stun: components["schemas"]["STUNServer"];
      /** @description Port to stream to. */
      port: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * Ping
   * @description Ping.
   */
  PingPing: {
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        headers: {
          "cache-control"?: string;
        };
        content: {
          "application/json": null;
        };
      };
    };
  };
  /**
   * Ping headers
   * @description Ping headers.
   */
  PingHeadping: {
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        headers: {
          "cache-control"?: string;
        };
        content: {
          "application/json": null;
        };
      };
    };
  };
  /**
   * Request a stream
   * @description Request a stream.
   */
  StreamStream: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StreamRequestData"];
      };
    };
    responses: {
      /** @description Document created, URL follows */
      201: {
        headers: {};
        content: {
          "application/json": components["schemas"]["StreamResponseData"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
      /** @description Conflict */
      409: {
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
}
